//! Differential: `Salt::stretch` and key derivation vs keripy `Salter` vectors.
//!
//! Vectors generated by `scripts/keripy_salt_gen.py` at the pin in
//! `scripts/KERIPY_PIN`. `temp` rows use the vector-speed cost; `low` rows
//! pin the real libsodium interactive parameters.
#![cfg(all(feature = "crypto", feature = "std"))]
#![allow(
    clippy::unwrap_used,
    reason = "integration test binary — unwrap documents the failing invariant"
)]

use cesr::core::matter::code::VerKeyCode;
use cesr::crypto::{Salt, Tier};
use serde::Deserialize;

#[derive(Deserialize)]
struct Vector {
    salt_qb64: String,
    path: String,
    cost: String,
    seed_hex: String,
    verkey_qb64: String,
    verkey_nt_qb64: String,
}

fn vectors() -> Vec<Vector> {
    include_str!("fixtures/keripy_salt_vectors.json")
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| serde_json::from_str(l).unwrap())
        .collect()
}

#[test]
fn keripy_salt_stretch_matches_temp_vectors() {
    for v in vectors().iter().filter(|v| v.cost == "temp") {
        let salt = Salt::from_qb64(&v.salt_qb64).unwrap();
        let seed = salt.stretch_temp(&v.path).unwrap();
        assert_eq!(hex::encode(*seed), v.seed_hex, "path {:?}", v.path);
    }
}

#[test]
fn keripy_salt_stretch_matches_low_tier_vectors() {
    for v in vectors().iter().filter(|v| v.cost == "low") {
        let salt = Salt::from_qb64(&v.salt_qb64).unwrap();
        let seed = salt.stretch(&v.path, Tier::Low).unwrap();
        assert_eq!(hex::encode(*seed), v.seed_hex, "path {:?}", v.path);
    }
}

#[test]
fn keripy_salt_derived_verkeys_match_vectors() {
    for v in vectors().iter().filter(|v| v.cost == "temp") {
        let salt = Salt::from_qb64(&v.salt_qb64).unwrap();
        let kp = salt.key_pair_temp(&v.path).unwrap();
        let vk = kp.verfer(VerKeyCode::Ed25519).unwrap();
        let vk_nt = kp.verfer(VerKeyCode::Ed25519N).unwrap();
        assert_eq!(vk.to_qb64(), v.verkey_qb64, "path {:?}", v.path);
        assert_eq!(vk_nt.to_qb64(), v.verkey_nt_qb64, "path {:?}", v.path);
    }
}
