//! Read-spine acceptance tests (spine spec §4 Test A): keripy-signed wire
//! bytes → [`EventMessage::parse`] → [`Signed`] → [`KeyState`] fold.
//!
//! The fixtures are raw keripy `messagize` output — body + framed `-V`
//! attachment group + `-A` controller indexed signatures — generated by
//! `scripts/keripy_spine_gen.py` (pinned env, see `scripts/KERIPY_PIN`).
//! Every asserted value below is pinned VERBATIM from that generator's
//! printed output; keripy's `Kever` fold is the oracle, so agreement here is
//! a genuine cross-implementation check, not a tautology. The transition
//! verifies keripy's real Ed25519 signatures inside the fold.
//!
//! Test names contain `keripy` so the nightly differential filter
//! (`cargo test --all-features keripy`) picks them up.
#![cfg(feature = "wire")]

use std::error::Error;

use cesr::Matter;
use cesr::keri::{Identifier, SigningThreshold};
use cesr::serder::EventMessage;
use keri::{KeyState, Signed};

type Fallible<T> = Result<T, Box<dyn Error>>;

const KERIPY_ICP_SIGNED: &[u8] = include_bytes!("fixtures/keripy_icp_signed.cesr");
const KERIPY_KEL_SIGNED: &[u8] = include_bytes!("fixtures/keripy_kel_signed.cesr");

// Pinned from `scripts/keripy_spine_gen.py` (keripy v2.0.0.dev5-1030-gde59bc7d).
const ICP_PREFIX: &str = "EAgiYKF60TEknM7KiRxL1GTDzJDceCi6h09CaoeSmS67";
const ICP_KEYS: [&str; 2] = [
    "DC9AyblHqFkfAH6-vPPL-dp6s0a4iYSURoqaNSS6V2e2",
    "DEtaUMSpw3Gh7P3afvHlt2lH6t24Dayqbzet6XgEfVb5",
];
const KEL_FINAL_SN: u128 = 2;
const KEL_FINAL_SAID: &str = "EKn6pBh5ZDiOL8245Xd2aVwkwyMU7xNDAKsxIodpK5qq";
const KEL_FINAL_KEYS: [&str; 2] = [
    "DCluRnI1EW8-baaxpM27Ka8iZd5JUMUH-tzcpwxn4ca-",
    "DN-Y5KRslZXlIDti9cqWqnKOBomdipM-PMp5xJDwetEn",
];
const KEL_FINAL_NEXT_KEYS: [&str; 2] = [
    "EPZ9ocOyx-T1yFjChEJAuovZ7eK-xe_9bwP4nFVbzGtR",
    "EPoRb6PUTQNrVWNbnTDrFXgmnxDXiDI8-FzJLoMO7QS5",
];

fn prefix_qb64(id: &Identifier<'_>) -> String {
    match id {
        Identifier::Basic(p) => p.to_qb64(),
        Identifier::SelfAddressing(s) => s.to_qb64(),
    }
}

#[test]
fn keripy_signed_inception_stream_folds_to_key_state() -> Fallible<()> {
    let (msg, rest) = EventMessage::parse(KERIPY_ICP_SIGNED)?;
    assert!(rest.is_empty(), "single-message stream leaves no remainder");
    assert_eq!(msg.sigs().len(), 2, "two controller indexed signatures");
    assert!(msg.wigs().is_empty(), "no witness receipts attached");

    let signed = Signed::from(&msg);
    let state = KeyState::incept(&signed)?;

    assert_eq!(prefix_qb64(state.prefix()), ICP_PREFIX);
    assert_eq!(state.keys().len(), 2);
    let keys: Vec<String> = state.keys().iter().map(Matter::to_qb64).collect();
    assert_eq!(keys, ICP_KEYS);
    assert_eq!(state.threshold(), &SigningThreshold::Simple(2));
    assert_eq!(state.next_threshold(), &SigningThreshold::Simple(2));
    assert_eq!(state.witness_threshold().value(), 0);
    assert!(state.witnesses().is_empty());
    Ok(())
}

#[test]
fn keripy_signed_kel_stream_folds_through_ingest() -> Fallible<()> {
    // Loop-parse the concatenated 3-message stream: each parse consumes
    // exactly one framed message and returns the remainder.
    let mut input = KERIPY_KEL_SIGNED;
    let mut messages = Vec::new();
    while !input.is_empty() {
        let (msg, rest) = EventMessage::parse(input)?;
        messages.push(msg);
        input = rest;
    }
    assert_eq!(messages.len(), 3, "icp + rot + ixn");

    let signed: Vec<Signed> = messages.iter().map(Signed::from).collect();
    let (genesis, rest) = signed.split_first().ok_or("KEL has a genesis event")?;
    let state = rest
        .iter()
        .try_fold(KeyState::incept(genesis)?, KeyState::ingest)?;

    assert_eq!(prefix_qb64(state.prefix()), ICP_PREFIX);
    assert_eq!(state.sn().value(), KEL_FINAL_SN);
    assert_eq!(state.latest_said().to_qb64(), KEL_FINAL_SAID);
    let keys: Vec<String> = state.keys().iter().map(Matter::to_qb64).collect();
    assert_eq!(keys, KEL_FINAL_KEYS);
    let next_keys: Vec<String> = state.next_keys().iter().map(Matter::to_qb64).collect();
    assert_eq!(next_keys, KEL_FINAL_NEXT_KEYS);
    assert_eq!(state.threshold(), &SigningThreshold::Simple(2));
    assert_eq!(state.witness_threshold().value(), 0);
    Ok(())
}
