//! Read-spine acceptance tests (spine spec §4 Test A): keripy-signed wire
//! bytes → [`EventMessage::parse`] → [`Signed`] → [`KeyState`] fold.
//!
//! The fixtures are raw keripy `messagize` output — body + framed `-V`
//! attachment group + `-A` controller indexed signatures — generated by
//! `scripts/keripy_spine_gen.py` (pinned env, see `scripts/KERIPY_PIN`).
//! Every asserted value below is pinned VERBATIM from that generator's
//! printed output; keripy's `Kever` fold is the oracle, so agreement here is
//! a genuine cross-implementation check, not a tautology. The transition
//! verifies keripy's real Ed25519 signatures inside the fold.
//!
//! Test names contain `keripy` so the nightly differential filter
//! (`cargo test --all-features keripy`) picks them up.
#![cfg(feature = "std")]

use std::error::Error;

use cesr::Matter;
use cesr::core::indexer::code::IndexMode;
use cesr::core::matter::code::{DigestCode, VerKeyCode};
use cesr::crypto::{Ed25519, KeyPair, digest};
use cesr::keri::{Identifier, SigningThreshold};
use cesr::stream::ControllerIdxSigs;
use keri::{KeyState, Rejection, Signed};
use keri_codec::{EventMessage, InceptionBuilder};

type Fallible<T> = Result<T, Box<dyn Error>>;

const KERIPY_ICP_SIGNED: &[u8] = include_bytes!("fixtures/keripy_icp_signed.cesr");
const KERIPY_KEL_SIGNED: &[u8] = include_bytes!("fixtures/keripy_kel_signed.cesr");
const KERIPY_ICP_WITNESSED: &[u8] = include_bytes!("fixtures/keripy_icp_witnessed.cesr");

// Pinned from `scripts/keripy_spine_gen.py` (keripy v2.0.0.dev5-1030-gde59bc7d).
const ICP_PREFIX: &str = "EAgiYKF60TEknM7KiRxL1GTDzJDceCi6h09CaoeSmS67";
const ICP_KEYS: [&str; 2] = [
    "DC9AyblHqFkfAH6-vPPL-dp6s0a4iYSURoqaNSS6V2e2",
    "DEtaUMSpw3Gh7P3afvHlt2lH6t24Dayqbzet6XgEfVb5",
];
const KEL_FINAL_SN: u128 = 2;
const KEL_FINAL_SAID: &str = "EKn6pBh5ZDiOL8245Xd2aVwkwyMU7xNDAKsxIodpK5qq";
const KEL_FINAL_KEYS: [&str; 2] = [
    "DCluRnI1EW8-baaxpM27Ka8iZd5JUMUH-tzcpwxn4ca-",
    "DN-Y5KRslZXlIDti9cqWqnKOBomdipM-PMp5xJDwetEn",
];
const KEL_FINAL_NEXT_KEYS: [&str; 2] = [
    "EPZ9ocOyx-T1yFjChEJAuovZ7eK-xe_9bwP4nFVbzGtR",
    "EPoRb6PUTQNrVWNbnTDrFXgmnxDXiDI8-FzJLoMO7QS5",
];
const WITNESSED_ICP_PREFIX: &str = "DIHoEqLYCQdXmhLCCxKhifkJrw2LyFIQaSGjZYGMnKTw";
const WITNESSED_ICP_WITNESSES: [&str; 3] = [
    "BNaQ-Tr-zS4y42ayLiPuUA7fP8LZGhHjPVW7j3AWBsQc",
    "BEjNuDs48ZrhujHaqz8gMu95JO21tuG39BNYMthsvkyx",
    "BMdRd2EH4NOKVtA5LTaWcOjJV4FYYMj4ozmaknj4wZHy",
];

fn prefix_qb64(id: &Identifier<'_>) -> String {
    match id {
        Identifier::Basic(p) => p.to_qb64(),
        Identifier::SelfAddressing(s) => s.to_qb64(),
    }
}

#[test]
fn keripy_signed_inception_stream_folds_to_key_state() -> Fallible<()> {
    let (msg, rest) = EventMessage::parse(KERIPY_ICP_SIGNED)?;
    assert!(rest.is_empty(), "single-message stream leaves no remainder");
    assert_eq!(msg.sigs().len(), 2, "two controller indexed signatures");
    assert!(msg.wigs().is_empty(), "no witness receipts attached");

    let signed = Signed::from(&msg);
    let state = KeyState::incept(&signed)?;

    assert_eq!(prefix_qb64(state.prefix()), ICP_PREFIX);
    assert_eq!(state.keys().len(), 2);
    let keys: Vec<String> = state.keys().iter().map(Matter::to_qb64).collect();
    assert_eq!(keys, ICP_KEYS);
    assert_eq!(state.threshold(), &SigningThreshold::Simple(2));
    assert_eq!(state.next_threshold(), &SigningThreshold::Simple(2));
    assert_eq!(state.witness_threshold().value(), 0);
    assert!(state.witnesses().is_empty());
    Ok(())
}

#[test]
fn keripy_witnessed_inception_stream_folds_to_key_state() -> Fallible<()> {
    // Spine phase 3: the fold verifies witness receipts. The fixture is a
    // keripy-witnessed inception (3 non-transferable witnesses, toad 2) with
    // receipts from witnesses 0 and 2 attached as a `-B` WitnessIdxSigs
    // group; keripy's own `Kever` accepted it (its constructor verifies the
    // wigers against the witness list and the toad, `eventing.py:2735-2799`),
    // so agreement here is a genuine cross-implementation check.
    let (msg, rest) = EventMessage::parse(KERIPY_ICP_WITNESSED)?;
    assert!(rest.is_empty(), "single-message stream leaves no remainder");
    assert_eq!(msg.sigs().len(), 1, "one controller indexed signature");
    assert_eq!(msg.wigs().len(), 2, "two witness receipts attached");

    let signed = Signed::from(&msg);
    let state = KeyState::incept(&signed)?;

    assert_eq!(prefix_qb64(state.prefix()), WITNESSED_ICP_PREFIX);
    let wits: Vec<String> = state.witnesses().iter().map(Matter::to_qb64).collect();
    assert_eq!(wits, WITNESSED_ICP_WITNESSES);
    assert_eq!(state.witness_threshold().value(), 2);
    Ok(())
}

#[test]
fn keripy_witnessed_inception_without_receipts_is_insufficient() -> Fallible<()> {
    // The same keripy fixture with its receipts withheld must be rejected
    // with the exact counts — the mirror of keripy escrowing the event as
    // partially witnessed (`escrowPWEvent` + `MissingWitnessSignatureError`,
    // `eventing.py:2788-2799`).
    let (msg, _) = EventMessage::parse(KERIPY_ICP_WITNESSED)?;
    let signed = Signed {
        wigs: vec![],
        ..Signed::from(&msg)
    };
    let Err(r) = KeyState::incept(&signed) else {
        return Err("a witnessed inception folded without its receipts".into());
    };
    assert!(matches!(
        r,
        Rejection::InsufficientWitnessReceipts {
            valid: 0,
            required: 2
        }
    ));
    Ok(())
}

#[test]
fn write_spine_framed_inception_folds_to_key_state() -> Fallible<()> {
    // The full round trip through both spines (spine spec §4 Test B, fold
    // half): build a fresh inception, sign it, frame it with the write
    // spine (`from_sigers` + `frame_v1`), parse it back with the read
    // spine, and fold it — the state must reproduce the built event's.
    let controller = KeyPair::<Ed25519>::generate()?;
    let next = KeyPair::<Ed25519>::generate()?;
    let verfer = controller.verfer(VerKeyCode::Ed25519)?.into_static();
    let next_digest = digest(
        DigestCode::Blake3_256,
        &next.verfer(VerKeyCode::Ed25519)?.to_qb64b(),
    )?;

    let event = InceptionBuilder::new()
        .keys(vec![verfer.clone()])
        .threshold(SigningThreshold::Simple(1))
        .next_keys(vec![next_digest])
        .next_threshold(SigningThreshold::Simple(1))
        .build()?;
    let sigers = vec![controller.sign_indexed(event.as_bytes(), 0, IndexMode::Both)?];
    let framed = event.frame_v1(&ControllerIdxSigs::from_sigers(&sigers)?, None)?;

    let (msg, rest) = EventMessage::parse(&framed)?;
    assert!(rest.is_empty(), "framed message leaves no remainder");
    let state = KeyState::incept(&Signed::from(&msg))?;

    assert_eq!(prefix_qb64(state.prefix()), event.said().to_qb64());
    let keys: Vec<String> = state.keys().iter().map(Matter::to_qb64).collect();
    assert_eq!(keys, vec![verfer.to_qb64()]);
    assert_eq!(state.threshold(), &SigningThreshold::Simple(1));
    assert_eq!(state.sn().value(), 0);
    Ok(())
}

#[test]
fn keripy_signed_kel_stream_folds_through_ingest() -> Fallible<()> {
    // Loop-parse the concatenated 3-message stream: each parse consumes
    // exactly one framed message and returns the remainder.
    let mut input = KERIPY_KEL_SIGNED;
    let mut messages = Vec::new();
    while !input.is_empty() {
        let (msg, rest) = EventMessage::parse(input)?;
        messages.push(msg);
        input = rest;
    }
    assert_eq!(messages.len(), 3, "icp + rot + ixn");

    let signed: Vec<Signed> = messages.iter().map(Signed::from).collect();
    let (genesis, rest) = signed.split_first().ok_or("KEL has a genesis event")?;
    let state = rest
        .iter()
        .try_fold(KeyState::incept(genesis)?, KeyState::ingest)?;

    assert_eq!(prefix_qb64(state.prefix()), ICP_PREFIX);
    assert_eq!(state.sn().value(), KEL_FINAL_SN);
    assert_eq!(state.latest_said().to_qb64(), KEL_FINAL_SAID);
    let keys: Vec<String> = state.keys().iter().map(Matter::to_qb64).collect();
    assert_eq!(keys, KEL_FINAL_KEYS);
    let next_keys: Vec<String> = state.next_keys().iter().map(Matter::to_qb64).collect();
    assert_eq!(next_keys, KEL_FINAL_NEXT_KEYS);
    assert_eq!(state.threshold(), &SigningThreshold::Simple(2));
    assert_eq!(state.witness_threshold().value(), 0);
    Ok(())
}
