//! Write-spine acceptance tests (spine spec §4 Test B): builder-constructed
//! event → sign → [`ControllerIdxSigs::from_sigers`] →
//! [`SerializedEvent::frame_v1`] → wire bytes.
//!
//! `framed_inception_is_byte_identical_to_keripy` is the strongest test in
//! the spine: it rebuilds keripy's fixture inception from the generator's
//! salt-derived Ed25519 seeds (`scripts/keripy_spine_gen.py`, pinned env per
//! `scripts/KERIPY_PIN`), re-signs it with `crypto`, frames it with
//! `frame_v1`, and asserts the COMPLETE framed message equals keripy's
//! `messagize` output (`keri/tests/fixtures/keripy_icp_signed.cesr`)
//! verbatim — builder, JSON writer, SAID, signing, group encoding, and
//! framing all proven against keripy byte-for-byte at once.
//!
//! Test names contain `keripy` where they consume keripy fixtures so the
//! nightly differential filter picks them up.
#![cfg(feature = "std")]

use std::error::Error;

use cesr::core::indexer::code::IndexMode;
use cesr::core::matter::builder::MatterBuilder;
use cesr::core::matter::code::{DigestCode, SeedCode, VerKeyCode};
use cesr::core::primitives::{Siger, Signer, Verfer};
use cesr::crypto::{Ed25519, KeyPair, digest};
use cesr::keri::{KeriEvent, SigningThreshold};
use cesr::stream::group::{ControllerIdxSigs, WitnessIdxSigs};
use keri_codec::{EventMessage, InceptionBuilder, SerializedEvent};

type Fallible<T> = Result<T, Box<dyn Error>>;

/// keripy `messagize` output for the fixture inception (body + framed `-V`
/// attachment + `-A` controller sigs), generated by
/// `scripts/keripy_spine_gen.py`.
const KERIPY_ICP_SIGNED: &[u8] = include_bytes!("fixtures/keripy_icp_signed.cesr");

// Pinned from `scripts/keripy_spine_gen.py` (keripy v2.0.0.dev5-1030-gde59bc7d):
// the raw Ed25519 private seeds keripy's `Salter(raw=b"spine-fixture-01")`
// derived. Seeds 0-1 sign the inception; seeds 2-3's verification keys are
// the next-key commitment preimages.
const ICP_SIGNING_SEEDS_HEX: [&str; 2] = [
    "992b1e0979a09938c3805b48777d3da8a24fa191c4c31ddcf5b7a436968ddd1a",
    "a2233d14c8e366dadcb68e6dccb58ab2e08bcf2e4efb6ad91125fc6e513b677d",
];
const ICP_NEXT_SEEDS_HEX: [&str; 2] = [
    "43261d9a7c54b129cae9aec9d360a17b8ef5ab1727a40a898cd741b4188cd8dc",
    "15094d01c372d7981a216507095b656f987428ed3a80fede213acde5f124d08c",
];
// The verification keys keripy derived from seeds 0-1 (sanity anchor that
// the seed → keypair derivation matches keripy before the byte assert).
const ICP_KEYS_QB64: [&str; 2] = [
    "DC9AyblHqFkfAH6-vPPL-dp6s0a4iYSURoqaNSS6V2e2",
    "DEtaUMSpw3Gh7P3afvHlt2lH6t24Dayqbzet6XgEfVb5",
];

fn decode_hex(s: &str) -> Fallible<Vec<u8>> {
    if !s.len().is_multiple_of(2) {
        return Err("hex string has odd length".into());
    }
    (0..s.len())
        .step_by(2)
        .map(|i| {
            u8::from_str_radix(s.get(i..i + 2).ok_or("hex slice out of bounds")?, 16)
                .map_err(Into::into)
        })
        .collect()
}

/// An Ed25519 keypair reconstructed from a keripy raw private seed.
fn keypair_from_seed_hex(seed_hex: &str) -> Fallible<KeyPair<Ed25519>> {
    let raw = decode_hex(seed_hex)?;
    let signer: Signer<'_> = MatterBuilder::new()
        .with_code(SeedCode::Ed25519Seed)
        .with_raw(raw)?
        .build()?;
    Ok(KeyPair::<Ed25519>::from_seed(&signer)?)
}

fn transferable_verfer(kp: &KeyPair<Ed25519>) -> Fallible<Verfer<'static>> {
    Ok(kp.verfer(VerKeyCode::Ed25519)?.into_static())
}

/// The Blake3-256 next-key commitment keripy computes:
/// `Diger(ser=verfer.qb64b)`.
fn commitment(verfer: &Verfer<'static>) -> Fallible<cesr::core::primitives::Diger<'static>> {
    Ok(digest(DigestCode::Blake3_256, &verfer.to_qb64b())?)
}

#[test]
fn framed_inception_is_byte_identical_to_keripy() -> Fallible<()> {
    let signing: Vec<KeyPair<Ed25519>> = ICP_SIGNING_SEEDS_HEX
        .iter()
        .map(|s| keypair_from_seed_hex(s))
        .collect::<Fallible<_>>()?;
    let keys: Vec<Verfer<'static>> = signing
        .iter()
        .map(transferable_verfer)
        .collect::<Fallible<_>>()?;
    let pinned_keys: Vec<String> = keys.iter().map(cesr::Matter::to_qb64).collect();
    assert_eq!(
        pinned_keys, ICP_KEYS_QB64,
        "seed → keypair derivation must match keripy's Salter output"
    );

    let next_keys = ICP_NEXT_SEEDS_HEX
        .iter()
        .map(|s| commitment(&transferable_verfer(&keypair_from_seed_hex(s)?)?))
        .collect::<Fallible<Vec<_>>>()?;

    let event = InceptionBuilder::new()
        .keys(keys)
        .threshold(SigningThreshold::Simple(2))
        .next_keys(next_keys)
        .next_threshold(SigningThreshold::Simple(2))
        .build()?;

    let sigers: Vec<Siger<'static>> = signing
        .iter()
        .enumerate()
        .map(|(i, kp)| Ok(kp.sign_indexed(event.as_bytes(), u32::try_from(i)?, IndexMode::Both)?))
        .collect::<Fallible<_>>()?;
    let sigs = ControllerIdxSigs::from_sigers(&sigers)?;

    let framed = event.frame_v1(&sigs, None)?;
    assert_eq!(
        framed, KERIPY_ICP_SIGNED,
        "complete framed message must equal keripy's messagize output verbatim"
    );
    Ok(())
}

#[test]
fn write_then_read_round_trips_through_the_spine() -> Fallible<()> {
    // Fresh cesr keypairs: one controller, one next-key commitment, one
    // non-transferable witness (keripy witness prefixes are Ed25519N).
    let controller = KeyPair::<Ed25519>::generate()?;
    let next = KeyPair::<Ed25519>::generate()?;
    let witness = KeyPair::<Ed25519>::generate()?;
    let witness_prefix = witness.verfer(VerKeyCode::Ed25519N)?.into_static();

    let event: SerializedEvent = InceptionBuilder::new()
        .keys(vec![transferable_verfer(&controller)?])
        .threshold(SigningThreshold::Simple(1))
        .next_keys(vec![commitment(&transferable_verfer(&next)?)?])
        .next_threshold(SigningThreshold::Simple(1))
        .witnesses(vec![witness_prefix])
        .witness_threshold(1)
        .build()?;

    let sigers = vec![controller.sign_indexed(event.as_bytes(), 0, IndexMode::Both)?];
    let wigers = vec![witness.sign_indexed(event.as_bytes(), 0, IndexMode::Both)?];
    let sigs = ControllerIdxSigs::from_sigers(&sigers)?;
    let wigs = WitnessIdxSigs::from_sigers(&wigers)?;

    let framed = event.frame_v1(&sigs, Some(&wigs))?;

    // The write spine's output parses back through the read spine with zero
    // re-encoding drift.
    let (msg, rest) = EventMessage::parse(&framed)?;
    assert!(rest.is_empty(), "framed message leaves no remainder");
    assert_eq!(
        msg.body(),
        event.as_bytes(),
        "parsed body is the exact signed span"
    );
    let KeriEvent::Inception(parsed) = msg.event() else {
        return Err("framed inception must parse as an inception".into());
    };
    assert_eq!(parsed.said().to_qb64(), event.said().to_qb64());

    let controller_parsed: Vec<String> = msg.sigs().iter().map(Siger::to_qb64).collect();
    let controller_written: Vec<String> = sigers.iter().map(Siger::to_qb64).collect();
    assert_eq!(
        controller_parsed, controller_written,
        "controller sigs round-trip"
    );
    let receipts_parsed: Vec<String> = msg.wigs().iter().map(Siger::to_qb64).collect();
    let receipts_written: Vec<String> = wigers.iter().map(Siger::to_qb64).collect();
    assert_eq!(
        receipts_parsed, receipts_written,
        "witness receipts round-trip"
    );
    Ok(())
}
