//! keripy differential vectors for the exn/IPEX lane (P4): the KERI `exn`
//! exchange envelope carrying the six IPEX routes — apply, offer, agree,
//! grant, admit, spurn — as keripy's `vc/protocoling.py` factories render
//! them at the pin (`scripts/KERIPY_PIN`, de59bc7d), replayed through the
//! **public** Rust API.
//!
//! The corpus is generated by `scripts/keripy_ipex_gen.py` in SHAPE
//! REPRODUCTION mode (the pinned keripy requires Python >= 3.14; see the
//! generator's docstring): the field order `v,t,d,i,rp,p,dt,r,q,a[,e]`,
//! the per-route payloads (`{m,s,a,i}` / `{m}` / `{m,i}`), the absent `e`
//! on `core.exchange` routes versus the always-present `e` on
//! `specialExchange` routes, the embeds map saidified per-label with its
//! own trailing `d`, and the embedded ACDC / TEL `iss` / KEL `ixn` bodies
//! are reproduced byte-for-byte, with real blake3-256 digests and a real
//! Ed25519 sender signature (`PyNaCl`). The corpus is marked PARTIAL in
//! `docs/keripy-parity/ledger.md` (spec risk 3: not generated by importing
//! keripy itself).
//!
//! Three families, one record per line:
//!
//! - `happy.jsonl` — every envelope deserializes through
//!   [`Exn::deserialize`] (SAID + embeds-map SAID + every embedded SAD
//!   verified over the generic SAD path), lifts into the typed
//!   [`IpexMessage`] at its route, and re-serializes byte-identical.
//! - `signed.jsonl` — the same envelopes signed by the sender: the
//!   reconstructed indexed signature verifies cryptographically, the
//!   framed message round-trips through [`Message::parse`]'s exn lane,
//!   and the typed lift re-parses from the framed body.
//! - `harden.jsonl` — parse-hardening vectors at two levels: `level:
//!   "exn"` rejects in [`Exn::deserialize`]; `level: "route"` parses as a
//!   generic envelope and is rejected by [`IpexMessage::parse`] with the
//!   law its `why` token names.
//!
//! Regenerate:
//!
//! ```text
//! python3 scripts/keripy_ipex_gen.py \
//!   --out-dir crates/keri-codec/tests/corpus/ipex
//! ```
//!
//! The corpus is embedded via `include_str!` because the nix gate builds
//! and runs tests in separate hermetic phases, so a runtime
//! `CARGO_MANIFEST_DIR` path is unreliable (same as the other corpora).
mod common;

use std::borrow::Cow;

use base64::Engine;
use base64::engine::general_purpose::STANDARD as BASE64;
use cesr::core::matter::builder::MatterBuilder;
use cesr::core::matter::code::VerKeyCode;
use cesr::core::primitives::Siger;
use cesr::crypto::{IndexedVerifyError, verify_indexed};
use cesr_stream::group::ControllerIdxSigs;
use keri_codec::{
    CodecError, Deserialize, DeserializeError, Exn, IpexMessage, IpexRoute, Message, Serialize,
};
use keri_events::VerifyingKey;

use common::{Fallible, siger_from_qb64};

const HAPPY: &str = include_str!("corpus/ipex/happy.jsonl");
const SIGNED: &str = include_str!("corpus/ipex/signed.jsonl");
const HARDEN: &str = include_str!("corpus/ipex/harden.jsonl");

/// The keripy pin every checked-in vector's shapes were reproduced from.
const KERIPY_PIN: &str = "de59bc7d834955c5b0273c62f6b8b6a0df150dc3";

#[derive(Debug, serde::Deserialize)]
struct HappyVector {
    case: String,
    route: String,
    raw: String,
}

#[derive(Debug, serde::Deserialize)]
struct SignedVector {
    case: String,
    route: String,
    raw: String,
    vk_b64: String,
    sig_qb64: String,
}

#[derive(Debug, serde::Deserialize)]
struct HardeningVector {
    case: String,
    route: String,
    level: String,
    why: String,
    raw: String,
}

/// One JSONL record per line; malformed corpus records abort the test
/// through `?` (no `expect` — the workspace denies it in tests too).
fn records(raw: &str) -> Fallible<Vec<serde_json::Value>> {
    raw.lines()
        .map(|line| serde_json::from_str(line).map_err(Into::into))
        .collect()
}

/// The sender's transferable Ed25519 verification key, rebuilt from the raw
/// standard-base64 bytes the generator records.
fn verifying_key(vk_b64: &str) -> Fallible<VerifyingKey<'static>> {
    let raw = BASE64.decode(vk_b64)?;
    let matter = MatterBuilder::new()
        .with_code(VerKeyCode::Ed25519)
        .with_raw(Cow::Owned(raw))?
        .build()?;
    Ok(VerifyingKey::from_matter(matter.into_static()))
}

/// The indexed-signature verification results for `sigs` over `body` under
/// `verfer` — the two consumer call sites (raw and reparsed) share the
/// reduction so both assertions stay uniform.
fn signature_results<'a>(
    verfer: &'a VerifyingKey<'a>,
    body: &'a [u8],
    sigs: impl IntoIterator<Item = &'a Siger<'a>> + 'a,
) -> Vec<Result<u32, IndexedVerifyError>> {
    verify_indexed(std::slice::from_ref(verfer.as_matter()), body, sigs).collect()
}

/// The typed lift every happy/signed record must survive, asserted against
/// the record's route and the shape facts the factories pin: offer embeds
/// its credential; grant embeds its credential with optional `iss`/`anc`;
/// replies carry a prior.
fn assert_route_shape(case: &str, route: &str, message: &IpexMessage<'_>) -> Fallible<()> {
    let expected =
        IpexRoute::from_route(route).ok_or_else(|| format!("{case}: unknown route {route}"))?;
    assert_eq!(
        message.route(),
        expected,
        "{case}: dispatched to the wrong typed route",
    );
    match message {
        IpexMessage::Apply(apply) => {
            assert!(!apply.message().is_empty(), "{case}: empty payload message");
            assert!(apply.prior().is_none(), "{case}: apply is an opener");
        }
        IpexMessage::Offer(offer) => {
            assert!(!offer.message().is_empty(), "{case}: empty payload message");
            assert!(offer.prior().is_none(), "{case}: offer is an opener");
        }
        IpexMessage::Agree(agree) => {
            assert!(!agree.message().is_empty(), "{case}: empty payload message");
            assert!(
                agree.prior().is_some(),
                "{case}: agree replies to the offer"
            );
        }
        IpexMessage::Grant(grant) => {
            assert!(!grant.message().is_empty(), "{case}: empty payload message");
            assert!(
                grant.prior().is_some(),
                "{case}: grant replies to the offer"
            );
            if case == "grant" {
                // The full grant embeds its TEL issuance and KEL anchor
                // alongside the credential.
                assert!(grant.iss().is_some(), "{case}: missing iss embed");
                assert!(grant.anc().is_some(), "{case}: missing anc embed");
            } else {
                assert!(grant.iss().is_none(), "{case}: unexpected iss embed");
                assert!(grant.anc().is_none(), "{case}: unexpected anc embed");
            }
        }
        IpexMessage::Admit(admit) => {
            assert!(!admit.message().is_empty(), "{case}: empty payload message");
            assert!(
                admit.prior().is_some(),
                "{case}: admit replies to the grant"
            );
        }
        IpexMessage::Spurn(spurn) => {
            assert!(!spurn.message().is_empty(), "{case}: empty payload message");
            assert!(spurn.prior().is_some(), "{case}: spurn names its prior");
        }
    }
    Ok(())
}

/// Does `err` carry the law `why` names? One arm per hardening family, so a
/// vector rejected by the WRONG law fails loudly instead of passing.
/// Envelope-level embeds-map SAID failures and outer SAID failures both
/// surface through `CodecError::Said`.
fn rejected_by(err: &CodecError, why: &str) -> bool {
    match why {
        "unknown_route" => {
            matches!(
                err,
                CodecError::Deserialize(DeserializeError::UnknownRoute(_))
            )
        }
        "unknown_embed" => {
            matches!(
                err,
                CodecError::Deserialize(DeserializeError::UnknownEmbed(_, _))
            )
        }
        "missing_field" => {
            matches!(
                err,
                CodecError::Deserialize(DeserializeError::MissingField(_))
            )
        }
        "attribute_said_form" => {
            matches!(
                err,
                CodecError::Deserialize(DeserializeError::AttributeSaidForm(_))
            )
        }
        "non_canonical" => {
            matches!(
                err,
                CodecError::Deserialize(DeserializeError::NonCanonical { .. })
            )
        }
        "said_mismatch" | "embeds_said_mismatch" => matches!(err, CodecError::Said(_)),
        _ => false,
    }
}

#[test]
fn happy_vectors_lift_typed_and_reserialize_byte_identical() -> Fallible<()> {
    let vectors = records(HAPPY)?;
    assert_eq!(vectors.len(), 7, "checked-in happy family is current");
    for value in vectors {
        let vector: HappyVector = serde_json::from_value(value)?;
        let exn = match Exn::deserialize(vector.raw.as_bytes()) {
            Ok(exn) => exn.into_static(),
            Err(err) => {
                return Err(format!(
                    "{} ({}): deserialize failed: {err}",
                    vector.case, vector.route
                )
                .into());
            }
        };
        // The typed lift dispatches on the route and strictly parses the
        // payload and typed embeds.
        let lifted = match IpexMessage::parse(&exn) {
            Ok(lifted) => lifted,
            Err(err) => {
                return Err(format!(
                    "{} ({}): typed lift failed: {err}",
                    vector.case, vector.route
                )
                .into());
            }
        };
        assert_route_shape(&vector.case, &vector.route, &lifted)?;

        // The parsed envelope re-serializes to the exact keripy-shaped
        // bytes — embeds included.
        let reserialized = exn.serialize()?.as_bytes().to_vec();
        assert_eq!(
            reserialized.as_slice(),
            vector.raw.as_bytes(),
            "{} ({}) does not reserialize byte-identical",
            vector.case,
            vector.route,
        );
    }
    Ok(())
}

#[test]
fn signed_vectors_verify_frame_and_relift() -> Fallible<()> {
    let vectors = records(SIGNED)?;
    assert_eq!(vectors.len(), 7, "checked-in signed family is current");
    for value in vectors {
        let vector: SignedVector = serde_json::from_value(value)?;
        let exn = match Exn::deserialize(vector.raw.as_bytes()) {
            Ok(exn) => exn.into_static(),
            Err(err) => {
                return Err(format!(
                    "{} ({}): deserialize failed: {err}",
                    vector.case, vector.route
                )
                .into());
            }
        };
        // The sender's key from the record verifies the reconstructed
        // indexed signature over the envelope bytes.
        let verfer = verifying_key(&vector.vk_b64)?;
        let siger = siger_from_qb64(&vector.sig_qb64)?;
        let verified = signature_results(&verfer, vector.raw.as_bytes(), std::iter::once(&siger));
        assert!(
            verified.iter().all(Result::is_ok),
            "{} ({}) signature does not verify: {verified:?}",
            vector.case,
            vector.route,
        );

        // Frame the signed message with the write spine and parse it back
        // with the read spine: the full public round trip through the exn
        // message lane.
        let framed = exn
            .serialize()?
            .frame_v1(&ControllerIdxSigs::from_indexed_signatures(&[siger])?)?;
        let (message, rest) = match Message::parse(&framed) {
            Ok(parsed) => parsed,
            Err(err) => {
                return Err(format!(
                    "{} ({}): framed parse failed: {err}",
                    vector.case, vector.route
                )
                .into());
            }
        };
        assert!(rest.is_empty(), "framed message leaves no remainder");
        let Message::Exn(lane) = &message else {
            return Err(format!(
                "{} ({}): dispatched to the wrong message lane",
                vector.case, vector.route,
            )
            .into());
        };
        assert_eq!(
            lane.body(),
            vector.raw.as_bytes(),
            "{} ({}) message body is not the signed span",
            vector.case,
            vector.route,
        );
        // The reparsed message's own signature re-verifies over its body.
        let reverified = signature_results(&verfer, lane.body(), lane.sigs().iter());
        assert!(
            reverified.iter().all(Result::is_ok),
            "{} ({}) reparsed signature does not verify: {reverified:?}",
            vector.case,
            vector.route,
        );
        // The typed lift works from the framed message's envelope too.
        let lifted = match IpexMessage::parse(lane.exn()) {
            Ok(lifted) => lifted,
            Err(err) => {
                return Err(format!(
                    "{} ({}): typed lift from framed message failed: {err}",
                    vector.case, vector.route
                )
                .into());
            }
        };
        assert_route_shape(&vector.case, &vector.route, &lifted)?;
    }
    Ok(())
}

#[test]
fn hardening_vectors_are_rejected_by_their_recorded_law() -> Fallible<()> {
    let vectors = records(HARDEN)?;
    assert_eq!(vectors.len(), 8, "checked-in hardening family is current");
    for value in vectors {
        let vector: HardeningVector = serde_json::from_value(value)?;
        match Exn::deserialize(vector.raw.as_bytes()) {
            Err(err) => {
                // Envelope-level rejection: the record must have said so.
                assert_eq!(
                    vector.level, "exn",
                    "{} ({}) rejected at the envelope but recorded as {}",
                    vector.case, vector.route, vector.level,
                );
                assert!(
                    rejected_by(&err, &vector.why),
                    "{} ({}) was rejected by the wrong law: {err:?} (expected '{}')",
                    vector.case,
                    vector.route,
                    vector.why,
                );
            }
            Ok(exn) => {
                let envelope = exn.into_static();
                // Route-level rejection: the envelope parses, the typed
                // lift must reject with the recorded law.
                assert_eq!(
                    vector.level, "route",
                    "{} ({}) parsed as an envelope but recorded as {}",
                    vector.case, vector.route, vector.level,
                );
                match IpexMessage::parse(&envelope) {
                    Ok(_) => {
                        return Err(format!(
                            "{} ({}): must be rejected by law '{}'",
                            vector.case, vector.route, vector.why,
                        )
                        .into());
                    }
                    Err(err) => assert!(
                        rejected_by(&err, &vector.why),
                        "{} ({}) was rejected by the wrong law: {err:?} (expected '{}')",
                        vector.case,
                        vector.route,
                        vector.why,
                    ),
                }
            }
        }
    }
    Ok(())
}

// The pin constant is asserted once so a drift between the corpus header
// and this consumer is caught at test time, not in review. The generator
// itself cannot be `include_str!`ed here: the nix gate's source filter
// keeps only Rust files plus `tests/corpus/` and `tests/fixtures/`, so a
// `scripts/` path fails to compile in the flake. Generator-side pin drift
// is guarded instead by the nightly keripy-diff workflow, which
// regenerates the corpus and lands any byte change as a visible diff.
#[test]
fn pinned_keripy_commit_is_current() {
    assert_eq!(KERIPY_PIN, "de59bc7d834955c5b0273c62f6b8b6a0df150dc3");
}
