//! keripy differential vectors for the TEL registry-event codec (P3): the
//! six registry ilks (vcp, vrt, iss, rev, bis, brv) as keripy's
//! `vdr/eventing.py` factories render them at the pin
//! (`scripts/KERIPY_PIN`, de59bc7d), replayed through the **public** Rust
//! API.
//!
//! The corpus is generated by `scripts/keripy_tel_gen.py` in SHAPE
//! REPRODUCTION mode (the pinned keripy requires Python >= 3.14; see the
//! generator's docstring): field orders, hexadecimal sequence/threshold
//! rendering, one-render vcp `d`/`i` SAIDs, and `SealEvent` `ra` anchors are
//! reproduced byte-for-byte, with real blake3-256 digests and real
//! Ed25519 issuer signatures (`PyNaCl`) — what keripy's `Saider` and
//! `ControllerIdxSigs` would emit. The corpus is marked PARTIAL in
//! `docs/keripy-parity/LEDGER.md` (spec risk 3: not generated by importing
//! keripy itself).
//!
//! Three families, one record per line:
//!
//! - `happy.jsonl` — every event deserializes through
//!   [`Deserialize`] (which verifies the SAID over the generic SAD path —
//!   no TEL-specific digest logic) and re-serializes byte-identical.
//! - `signed.jsonl` — the same events signed by the issuer: the
//!   reconstructed indexed signature verifies cryptographically, the
//!   framed message round-trips through [`Message::parse`], and the parsed
//!   message's body and signature re-verify over its own byte span.
//! - `harden.jsonl` — parse-hardening vectors, each rejected by the
//!   specific law its `why` token names.
//!
//! Regenerate:
//!
//! ```text
//! python3 scripts/keripy_tel_gen.py \
//!   --out-dir crates/keri-codec/tests/corpus/tel
//! ```
//!
//! The corpus is embedded via `include_str!` because the nix gate builds
//! and runs tests in separate hermetic phases, so a runtime
//! `CARGO_MANIFEST_DIR` path is unreliable (same as the other corpora).
mod common;

use std::borrow::Cow;

use base64::Engine;
use base64::engine::general_purpose::STANDARD as BASE64;
use cesr::core::matter::builder::MatterBuilder;
use cesr::core::matter::code::VerKeyCode;
use cesr::crypto::verify_indexed;
use cesr_stream::group::ControllerIdxSigs;
use keri_codec::{BuilderError, CodecError, Deserialize, DeserializeError, Message, Serialize};
use keri_events::{TelEvent, VerifyingKey};

use common::{Fallible, siger_from_qb64};

const HAPPY: &str = include_str!("corpus/tel/happy.jsonl");
const SIGNED: &str = include_str!("corpus/tel/signed.jsonl");
const HARDEN: &str = include_str!("corpus/tel/harden.jsonl");

/// The keripy pin every checked-in vector's shapes were reproduced from.
const KERIPY_PIN: &str = "de59bc7d834955c5b0273c62f6b8b6a0df150dc3";

#[derive(Debug, serde::Deserialize)]
struct HappyVector {
    case: String,
    ilk: String,
    raw: String,
}

#[derive(Debug, serde::Deserialize)]
struct SignedVector {
    case: String,
    ilk: String,
    raw: String,
    vk_b64: String,
    sig_qb64: String,
}

#[derive(Debug, serde::Deserialize)]
struct HardeningVector {
    case: String,
    ilk: String,
    why: String,
    raw: String,
}

/// One JSONL record per line; malformed corpus records abort the test
/// through `?` (no `expect` — the workspace denies it in tests too).
fn records(raw: &str) -> Fallible<Vec<serde_json::Value>> {
    raw.lines()
        .map(|line| serde_json::from_str(line).map_err(Into::into))
        .collect()
}

/// The issuer's transferable Ed25519 verification key, rebuilt from the raw
/// standard-base64 bytes the generator records.
fn verifying_key(vk_b64: &str) -> Fallible<VerifyingKey<'static>> {
    let raw = BASE64.decode(vk_b64)?;
    let matter = MatterBuilder::new()
        .with_code(VerKeyCode::Ed25519)
        .with_raw(Cow::Owned(raw))?
        .build()?;
    Ok(VerifyingKey::from_matter(matter.into_static()))
}

/// Does `err` carry the law `why` names? One arm per hardening family, so a
/// vector rejected by the WRONG law fails loudly instead of passing.
fn rejected_by(err: &CodecError, why: &str) -> bool {
    // One arm per hardening family, so a vector rejected by the WRONG law
    // fails loudly instead of passing. The scanner expresses a field-order
    // violation as NonCanonical too — the payload names the expected next
    // field (e.g. `,"ri":`).
    match why {
        "registry_identity" => {
            matches!(
                err,
                CodecError::Deserialize(DeserializeError::RegistryIdentifierMismatch)
            )
        }
        "pinned_sequence" => {
            matches!(
                err,
                CodecError::Deserialize(DeserializeError::TelSequenceDomain { .. })
            )
        }
        "toad_bounds" => matches!(
            err,
            CodecError::Deserialize(DeserializeError::BackerThresholdOutOfRange { .. })
        ),
        "non_canonical" | "field_order" => {
            matches!(
                err,
                CodecError::Deserialize(DeserializeError::NonCanonical { .. })
            )
        }
        "said_mismatch" => matches!(err, CodecError::Said(_)),
        "unknown_ilk" => {
            matches!(
                err,
                CodecError::Deserialize(DeserializeError::UnknownMessageType(_))
            )
        }
        "anchor_shape" => matches!(err, CodecError::Builder(BuilderError::NonEventBackerAnchor)),
        _ => false,
    }
}

#[test]
fn happy_vectors_deserialize_and_reserialize_byte_identical() -> Fallible<()> {
    let vectors = records(HAPPY)?;
    assert_eq!(vectors.len(), 7, "checked-in happy family is current");
    for value in vectors {
        let vector: HappyVector = serde_json::from_value(value)?;
        let event = match TelEvent::deserialize(vector.raw.as_bytes()) {
            Ok(event) => event.into_static(),
            Err(err) => {
                return Err(format!(
                    "{} ({}): deserialize failed: {err}",
                    vector.case, vector.ilk
                )
                .into());
            }
        };
        // The parsed event re-serializes to the exact keripy-shaped bytes.
        let reserialized = event.serialize()?.as_bytes().to_vec();
        assert_eq!(
            reserialized.as_slice(),
            vector.raw.as_bytes(),
            "{} ({}) does not reserialize byte-identical",
            vector.case,
            vector.ilk,
        );
    }
    Ok(())
}

#[test]
fn signed_vectors_verify_and_frame_and_reparse() -> Fallible<()> {
    let vectors = records(SIGNED)?;
    assert_eq!(vectors.len(), 7, "checked-in signed family is current");
    for value in vectors {
        let vector: SignedVector = serde_json::from_value(value)?;
        let event = match TelEvent::deserialize(vector.raw.as_bytes()) {
            Ok(event) => event.into_static(),
            Err(err) => {
                return Err(format!(
                    "{} ({}): deserialize failed: {err}",
                    vector.case, vector.ilk
                )
                .into());
            }
        };
        // The issuer's key from the record verifies the reconstructed
        // indexed signature over the event bytes.
        let verfer = verifying_key(&vector.vk_b64)?;
        let siger = siger_from_qb64(&vector.sig_qb64)?;
        let verified: Vec<_> = verify_indexed(
            std::slice::from_ref(verfer.as_matter()),
            vector.raw.as_bytes(),
            std::iter::once(&siger),
        )
        .collect();
        assert!(
            verified.iter().all(Result::is_ok),
            "{} ({}) signature does not verify: {verified:?}",
            vector.case,
            vector.ilk,
        );

        // Frame the signed message with the write spine and parse it back
        // with the read spine: the full public round trip.
        let framed = event
            .serialize()?
            .frame_v1(&ControllerIdxSigs::from_indexed_signatures(&[siger])?, None)?;
        let (message, rest) = match Message::parse(&framed) {
            Ok(parsed) => parsed,
            Err(err) => {
                return Err(format!(
                    "{} ({}): framed parse failed: {err}",
                    vector.case, vector.ilk
                )
                .into());
            }
        };
        assert!(rest.is_empty(), "framed message leaves no remainder");
        let Message::Tel(tel) = &message else {
            return Err(format!(
                "{} ({}): dispatched to the wrong message lane",
                vector.case, vector.ilk,
            )
            .into());
        };
        assert_eq!(
            tel.body(),
            vector.raw.as_bytes(),
            "{} ({}) message body is not the signed span",
            vector.case,
            vector.ilk,
        );
        // The reparsed message's own signature re-verifies over its body.
        let reverified: Vec<_> = verify_indexed(
            std::slice::from_ref(verfer.as_matter()),
            tel.body(),
            tel.sigs().iter(),
        )
        .collect();
        assert!(
            reverified.iter().all(Result::is_ok),
            "{} ({}) reparsed signature does not verify: {reverified:?}",
            vector.case,
            vector.ilk,
        );
    }
    Ok(())
}

#[test]
fn hardening_vectors_are_rejected_by_their_recorded_law() -> Fallible<()> {
    let vectors = records(HARDEN)?;
    assert_eq!(vectors.len(), 10, "checked-in hardening family is current");
    for value in vectors {
        let vector: HardeningVector = serde_json::from_value(value)?;
        match TelEvent::deserialize(vector.raw.as_bytes()) {
            Ok(_) => {
                return Err(format!(
                    "{} ({}): must be rejected by law '{}'",
                    vector.case, vector.ilk, vector.why,
                )
                .into());
            }
            Err(err) => assert!(
                rejected_by(&err, &vector.why),
                "{} ({}) was rejected by the wrong law: {err:?} (expected '{}')",
                vector.case,
                vector.ilk,
                vector.why,
            ),
        }
    }
    Ok(())
}

// The pin constant is asserted once so a drift between the generator and
// this consumer is caught at test time, not in review.
#[test]
fn corpus_pin_matches_the_generator() {
    assert_eq!(KERIPY_PIN, "de59bc7d834955c5b0273c62f6b8b6a0df150dc3");
    let generator = include_str!("../../../scripts/keripy_tel_gen.py");
    assert!(
        generator.contains(&format!("KERIPY_PIN = \"{KERIPY_PIN}\"")),
        "scripts/keripy_tel_gen.py pin drifted from the consumer",
    );
}
