#!/usr/bin/env python3
"""keripy ACDC parity generator (P4): deterministic happy + parse-hardening
vectors for the ACDC v1 credential SAD (keripy `SerderACDC`, protocol
`Protocols.acdc`).

Mode: SHAPE REPRODUCTION at the keripy pin. The pinned keripy checkout
(`scripts/KERIPY_PIN`, de59bc7d) requires Python >= 3.14 (`setup.py`
`python_requires='>=3.14.0'`) while this environment has 3.13, so this
generator does NOT import keripy — the one pinned pip attempt fails with
"Package 'keri' requires a different Python: 3.13.14 not in '>=3.14.0'".
Instead it reproduces the pinned factory's wire shapes byte-for-byte from
`src/keri/core/serdering.py` `SerderACDC` and `src/keri/vc/proving.py`
`credential` at the pin:

- version string: protocol `ACDC`, major 1, minor 0, JSON, explicit size —
  `ACDC10JSON{size:06x}_` (a 17-character version string);
- field order `v,d,u?,i?,ri?,s,a?,e?,r?,p?` (the aggregate forms `A`/`E`/`R`
  are not in this corpus: their digest derivation was not verified against
  the pin and the vector rule is to never guess);
- SAID derivation per keripy `Saider.saidify`: the `d` slot is replaced with
  a same-width dummy, the version size is patched, and blake3-256 over the
  whole body yields the `E...` qb64 spliced back in;
- nested blocks (schema/attributes/edges/rules) are saidified
  independently, inner-out, as bare canonical JSON objects: no version
  string, no size patch — the `d` dummy is replaced, blake3-256 runs over
  the map, and the digest splices back;
- edge groups per the verified ACDC draft shape: the group map is
  SAIDified, each edge leaf is a map carrying `n` (the target node SAID);
  no `sad`/`nest` fields (unverified — see docs/keripy-parity/ledger.md);
- explicit `dt`-free determinism: no wall-clock anywhere; `u` nonces and
  issuer prefixes derive from sha256 of fixed domain strings.

The SAIDs and signatures are REAL digests and real Ed25519 signatures —
independent `blake3` + `PyNaCl` reproduce exactly what keripy's `Saider`
and `ControllerIdxSigs` would emit — so the vectors are a genuine
wire-format differential, not placeholders. The corpus is marked PARTIAL
in `docs/keripy-parity/ledger.md` because it was not generated by
importing keripy itself (spec risk 3).

Output (JSONL, one record per line):
- `happy.jsonl`:  shape vectors —
  {"case", "form", "kind": "event", "raw", "reserialize": "identical"}
- `signed.jsonl`: the same credentials signed by the issuer —
  {"case", "form", "kind": "message", "raw", "vk_b64", "sig_qb64"}
- `harden.jsonl`: parse-hardening vectors —
  {"case", "form", "expect": "reject", "why", "raw"}

Determinism: every seed is sha256 of a fixed domain string; credentials
derive purely from those seeds. Re-running reproduces the corpora
byte-for-byte.

Regenerate:

    python3 scripts/keripy_acdc_gen.py \
      --out-dir crates/keri-codec/tests/corpus/acdc
"""

import argparse
import base64
import hashlib
import json
from pathlib import Path

import blake3
from nacl.signing import SigningKey

KERIPY_PIN = "de59bc7d834955c5b0273c62f6b8b6a0df150dc3"

SAID_LEN = 44  # `E` code byte + 32-byte digest = 33 qb2 bytes = 44 sextets
SAID_DUMMY = "#" * SAID_LEN

# CESR base64url alphabet.
B64URL = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"

HAPPY = "happy.jsonl"
SIGNED = "signed.jsonl"
HARDEN = "harden.jsonl"


def qb64(code: str, raw: bytes) -> str:
    """CESR qb64 for `raw` under selector `code`, per keripy `Matter`: the
    code's sextets are left-aligned in their qb2 bytes and the raw bytes
    follow BYTE-ALIGNED — for one-sextet codes the code byte is the sextet
    value shifted into the top 6 bits, then the raw stream. Not `code +
    b64(raw)`: that shifts the raw by 2 bits and produces a different
    (invalid) primitive."""
    acc, bits = 0, 0
    for ch in code:
        acc = (acc << 6) | B64URL.index(ch)
        bits += 6
    pad = (-bits) % 8
    code_bytes = (acc << pad).to_bytes((bits + pad) // 8, "big")
    return base64.urlsafe_b64encode(code_bytes + raw).decode().rstrip("=")


def domain_seed(name: str) -> bytes:
    return hashlib.sha256(b"keripy-acdc-parity:" + name.encode()).digest()


def issuer_prefix() -> str:
    """The issuer's transferable Ed25519 verification key qb64 (`D` + 43)."""
    raw = SigningKey(domain_seed("issuer")).verify_key.encode()
    return qb64("D", raw)


def issuee_prefix() -> str:
    """The issuee's transferable Ed25519 prefix qb64 (`D` + 43)."""
    raw = SigningKey(domain_seed("issuee")).verify_key.encode()
    return qb64("D", raw)


def schema_said(index: int) -> str:
    """A Blake3-256 schema SAID qb64 (`E` + 43) over fixed domain bytes —
    the compact form references a schema cached out of band."""
    digest = blake3.blake3(domain_seed(f"schema-{index}")).digest()
    return qb64("E", digest)


def registry_said() -> str:
    """A Blake3-256 registry SAID qb64 (`E` + 43) — the `ri` v1 reference
    to the issuer's TEL registry."""
    digest = blake3.blake3(domain_seed("registry")).digest()
    return qb64("E", digest)


def target_said(index: int) -> str:
    """A Blake3-256 chain-target SAID qb64 (`E` + 43) for edge leaves."""
    digest = blake3.blake3(domain_seed(f"target-{index}")).digest()
    return qb64("E", digest)


def nonce_qb64() -> str:
    """A Salt_128 salty-uuid nonce qb64 (`0A` + 22 over 16 raw bytes)."""
    raw = domain_seed("nonce")[:16]
    return qb64("0A", raw)


def issuer_signing_key() -> SigningKey:
    return SigningKey(domain_seed("issuer"))


def saidify_bare_map(mkd: dict) -> bytes:
    """Saidify one bare canonical JSON object per keripy `Saider.saidify`:
    no version string, no size patch — digest the map with the `d` slot
    dummied and splice the resulting `E...` qb64 back in.

    Self-checking: after splicing, the slot is re-dummied and re-digested
    to confirm the recorded SAID reproduces (keripy's `Saider.verify`
    contract)."""
    raw = json.dumps(mkd, separators=(",", ":"), ensure_ascii=False).encode()
    digest = blake3.blake3(raw).digest()
    said = qb64("E", digest)
    assert len(said) == SAID_LEN, "said width must be 44"
    slot = f'"d":"{SAID_DUMMY}"'.encode()
    assert slot in raw, "bare map must carry a dummied d slot"
    spliced = raw.replace(slot, f'"d":"{said}"'.encode())
    # Self-check: re-dummy and confirm the digest reproduces.
    scratch = spliced.replace(f'"d":"{said}"'.encode(), slot)
    assert blake3.blake3(scratch).digest() == digest, "SAID self-check failed"
    return spliced


def saidify_credential(ked: dict) -> bytes:
    """Saidify one canonical credential body per keripy `SerderACDC`
    `makify`: patch the version size, digest the body with the `d` slot
    dummied, and splice the resulting `E...` qb64 back in. Nested blocks
    must already carry their FINAL saidified bytes (inner-out).

    Self-checking: after splicing, the slot is re-dummied and re-digested
    to confirm the recorded SAID reproduces, and the version string is
    confirmed to record the body's own byte size."""
    raw = json.dumps(ked, separators=(",", ":"), ensure_ascii=False).encode()
    head = b'{"v":"ACDC10JSON000000_"'
    assert raw.startswith(head), "version placeholder"
    size = len(raw)
    raw = f'{{"v":"ACDC10JSON{size:06x}_"'.encode() + raw[len(head):]
    digest = blake3.blake3(raw).digest()
    said = qb64("E", digest)
    assert len(said) == SAID_LEN, "said width must be 44"
    slot = f'"d":"{SAID_DUMMY}"'.encode()
    assert slot in raw, "credential must carry a dummied d slot"
    spliced = raw.replace(slot, f'"d":"{said}"'.encode(), 1)
    # Self-check: re-dummy and confirm the digest reproduces.
    scratch = spliced.replace(f'"d":"{said}"'.encode(), slot, 1)
    assert blake3.blake3(scratch).digest() == digest, "SAID self-check failed"
    decoded = json.loads(spliced)
    assert decoded["v"] == f"ACDC10JSON{len(spliced):06x}_", (
        "version size self-check failed"
    )
    return spliced


def said_of(raw: bytes) -> str:
    """The recorded `d` qb64 of a finished credential body."""
    start = raw.index(b'"d":"') + 5
    return raw[start : start + SAID_LEN].decode()


def sign(raw: bytes) -> dict:
    """The issuer's Ed25519 signature over the final credential bytes, as
    keripy `messagize` attaches it: an indexed-sig qb64 (`A` + index sextet
    + 86, key index 0) plus the issuer's raw verification key for
    independent replay."""
    signed = issuer_signing_key().sign(raw)
    # Ed25519 indexed signature: selector `A` + one index sextet (`A` = key
    # index 0) + the 64-byte signature — 88 qb64 chars, byte-aligned.
    sig_qb64 = qb64("AA", signed.signature)
    assert len(sig_qb64) == 88, "indexed Ed25519 signature qb64 must be 88"
    return {
        "vk_b64": base64.b64encode(
            issuer_signing_key().verify_key.encode()
        ).decode(),
        "sig_qb64": sig_qb64,
    }


def schema_block() -> bytes:
    """An expanded schema block: a bare SAIDified map (inner-out first)."""
    return saidify_bare_map(
        {
            "d": SAID_DUMMY,
            "type": "Report",
            "version": "1.0.0",
        }
    )


def attributes_block() -> bytes:
    """An expanded attributes block: `a.i` names the issuee (keripy
    `attrib`/`issuee`)."""
    return saidify_bare_map(
        {
            "d": SAID_DUMMY,
            "i": issuee_prefix(),
            "title": "Quarterly report",
        }
    )


def edges_block() -> bytes:
    """An expanded edges block per the verified ACDC draft shape: the
    group map is SAIDified; each edge leaf is a map carrying `n`, the
    target node's SAID. No `sad`/`nest` fields — unverified forms are not
    in this corpus (docs/keripy-parity/ledger.md)."""
    return saidify_bare_map(
        {
            "d": SAID_DUMMY,
            "report": {
                "n": target_said(0),
            },
        }
    )


def rules_block() -> bytes:
    """An expanded rules block: a generic SAIDified map (keripy treats
    rules as opaque field maps at the Serder level)."""
    return saidify_bare_map(
        {
            "d": SAID_DUMMY,
            "usage": {
                "legal": "Revocable by the issuer at any time.",
            },
        }
    )


def compact_minimal() -> dict:
    """The most compact credential: schema as a bare SAID, nothing else
    optional present."""
    return {
        "v": "ACDC10JSON000000_",
        "d": SAID_DUMMY,
        "s": schema_said(0),
    }


def compact_issuance() -> dict:
    """Compact issuance form: issuer + registry + bare-SAID schema +
    inline attributes + chained-data prior."""
    return {
        "v": "ACDC10JSON000000_",
        "d": SAID_DUMMY,
        "u": nonce_qb64(),
        "i": issuer_prefix(),
        "ri": registry_said(),
        "s": schema_said(1),
        "a": json.loads(attributes_block()),
        "e": json.loads(edges_block()),
        "p": target_said(2),
    }


def expanded_issuance() -> dict:
    """Full expanded issuance form: schema, attributes, edges, and rules
    all inline blocks, each saidified inner-out."""
    return {
        "v": "ACDC10JSON000000_",
        "d": SAID_DUMMY,
        "u": nonce_qb64(),
        "i": issuer_prefix(),
        "ri": registry_said(),
        "s": json.loads(schema_block()),
        "a": json.loads(attributes_block()),
        "e": json.loads(edges_block()),
        "r": json.loads(rules_block()),
    }


def happy_vectors() -> list:
    """(case, form, raw) tuples — the happy-path credentials."""
    cases = [
        ("compact_minimal", "compact", compact_minimal()),
        ("compact_issuance", "compact", compact_issuance()),
        ("expanded_issuance", "expanded", expanded_issuance()),
    ]
    out = []
    for case, form, ked in cases:
        raw = saidify_credential(ked)
        out.append((case, form, raw))
    return out


def harden_vectors() -> list:
    """(case, form, why, raw) tuples — parse-hardening rejects, each named
    by the law it violates."""

    def reordered() -> bytes:
        # `s` before `d` violates the fixed SerderACDC field order.
        ked = compact_minimal()
        moved = {
            "v": ked["v"],
            "s": ked["s"],
            "d": SAID_DUMMY,
        }
        raw = json.dumps(moved, separators=(",", ":")).encode()
        size = len(raw)
        return f'{{"v":"ACDC10JSON{size:06x}_"'.encode() + raw[len(
            b'{"v":"ACDC10JSON000000_"'
        ):]

    def tampered() -> bytes:
        raw = saidify_credential(expanded_issuance())
        said = said_of(raw)
        other = qb64("E", blake3.blake3(domain_seed("tamper")).digest())
        assert other != said, "tamper digest must differ"
        return raw.replace(said.encode(), other.encode())

    def missing_schema() -> bytes:
        ked = compact_minimal()
        del ked["s"]
        raw = json.dumps(ked, separators=(",", ":")).encode()
        size = len(raw)
        return f'{{"v":"ACDC10JSON{size:06x}_"'.encode() + raw[len(
            b'{"v":"ACDC10JSON000000_"'
        ):]

    def unknown_field() -> bytes:
        ked = compact_minimal()
        ked["x"] = "surprise"
        return saidify_credential(ked)

    def wrong_protocol() -> bytes:
        # A KERI version string on an ACDC body: the head grammar pins
        # protocol `ACDC`.
        ked = compact_minimal()
        raw = json.dumps(ked, separators=(",", ":")).encode()
        size = len(raw)
        return f'{{"v":"KERI10JSON{size:06x}_"'.encode() + raw[len(
            b'{"v":"ACDC10JSON000000_"'
        ):]

    def broken_nested_said() -> bytes:
        # The inline edges block's own `d` fails verification: its bytes
        # were spliced against a different map.
        ked = expanded_issuance()
        ked["e"] = json.loads(edges_block())
        ked["e"]["tampered"] = ked["e"].pop("report")
        raw = saidify_credential(ked)
        return raw

    return [
        ("reordered_fields", "compact", "non_canonical", reordered()),
        ("tampered_said", "expanded", "said_mismatch", tampered()),
        ("missing_schema", "compact", "non_canonical", missing_schema()),
        ("unknown_field", "compact", "non_canonical", unknown_field()),
        ("wrong_protocol_version", "compact", "version_grammar", wrong_protocol()),
        ("broken_nested_said", "expanded", "nested_said_mismatch", broken_nested_said()),
    ]


def signed_records(happy: list) -> list:
    """The happy credentials signed by the issuer (keripy `messagize`
    content)."""
    records = []
    for case, form, raw in happy:
        record = {"case": case, "form": form, "kind": "message", "raw": raw.decode()}
        record.update(sign(raw))
        records.append(record)
    return records


def write_jsonl(path: Path, records: list) -> None:
    with open(path, "w", newline="\n") as handle:
        for record in records:
            handle.write(json.dumps(record, separators=(",", ":")) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="keripy ACDC parity generator (P4)")
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("crates/keri-codec/tests/corpus/acdc"),
        help="corpus output directory (default: the checked-in ACDC corpus)",
    )
    args = parser.parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)

    happy = happy_vectors()
    harden = harden_vectors()

    happy_records = [
        {
            "case": case,
            "form": form,
            "kind": "event",
            "raw": raw.decode(),
            "reserialize": "identical",
        }
        for case, form, raw in happy
    ]
    harden_records = [
        {
            "case": case,
            "form": form,
            "expect": "reject",
            "why": why,
            "raw": raw.decode(),
        }
        for case, form, why, raw in harden
    ]

    write_jsonl(args.out_dir / HAPPY, happy_records)
    write_jsonl(args.out_dir / SIGNED, signed_records(happy))
    write_jsonl(args.out_dir / HARDEN, harden_records)

    total = len(happy_records) + len(harden_records)
    print(f"wrote {total} vectors to {args.out_dir}:")
    print(f"  {HAPPY}: {len(happy_records)} happy-path credentials")
    print(f"  {SIGNED}: {len(happy_records)} issuer-signed messages")
    print(f"  {HARDEN}: {len(harden_records)} parse-hardening rejects")
    print(f"keripy pin (shapes reproduced from, not imported): {KERIPY_PIN}")


if __name__ == "__main__":
    main()
