#!/usr/bin/env python3
"""keripy IPEX parity generator (P4): deterministic happy + parse-hardening
vectors for the KERI `exn` exchange envelope carrying the six IPEX routes
(keripy `src/keri/vc/protocoling.py` factories over `core/exchanging.py`
`Exchange` + `specialExchange`).

Mode: SHAPE REPRODUCTION at the keripy pin. The pinned keripy checkout
(`scripts/KERIPY_PIN`, de59bc7d) requires Python >= 3.14 (`setup.py`
`python_requires='>=3.14.0'`) while this environment has 3.13, so this
generator does NOT import keripy — the one pinned pip attempt fails with
"Package 'keri' requires a different Python: 3.13.14 not in '>=3.14.0'".
Instead it reproduces the pinned factories' wire shapes byte-for-byte:

- version string: protocol `KERI`, major 1, minor 0, JSON, explicit size —
  `KERI10JSON{size:06x}_` (exchange rides the KERI protocol);
- field order `v,t,d,i,rp,p,dt,r,q,a[,e]` — `core.exchange` (apply, agree,
  admit, spurn) omits `e`; `peer.specialExchange` (offer, grant) always
  carries it (empty `{}` when no embeds — offer always embeds an ACDC);
- `rp` and `q` are empty on every factory; `p` is empty on conversation
  openers (apply, offer) and the prior message's SAID on replies;
- `dt` uses keripy's `nowiso` shape with a fixed deterministic timestamp;
- the embeds map is independently SAIDified per keripy `Saider.saidify`:
  entries in route order, then the map's own `"d": DUMMY` LAST — no
  version string, no size patch, blake3-256 over the bare map, digest
  spliced back;
- the outer envelope is saidified per `SerderKERI.makify`: the size is
  patched, blake3-256 runs over the whole body with only the top `d`
  dummied (the embeds map is already final inside it), and the digest
  splices back;
- route payloads per `protocoling.py`: apply `a={m,s,a,i}`; offer
  `a={m}`; agree `a={m}`; grant `a={m,i}`; admit `a={m}`; spurn `a={m}`;
- grant embeds `e={acdc, iss?, anc?}`: `acdc` is a full saidified ACDC
  credential body, `iss` a full saidified TEL `iss` event body (typed on
  the Rust side), `anc` a saidified KEL `ixn` anchor body (generic block
  on the Rust side);
- `a` itself is NOT independently SAIDified — it is a plain payload map
  inside the envelope.

The SAIDs and signatures are REAL digests and real Ed25519 signatures —
independent `blake3` + `PyNaCl` reproduce exactly what keripy's `Saider`
and `ControllerIdxSigs` would emit — so the vectors are a genuine
wire-format differential, not placeholders. The corpus is marked PARTIAL
in `docs/keripy-parity/ledger.md` because it was not generated by
importing keripy itself (spec risk 3).

Output (JSONL, one record per line):
- `happy.jsonl`:  shape vectors —
  {"case", "route", "kind": "event", "raw", "reserialize": "identical"}
- `signed.jsonl`: the same envelopes signed by the sender —
  {"case", "route", "kind": "message", "raw", "vk_b64", "sig_qb64"}
- `harden.jsonl`: parse-hardening vectors —
  {"case", "route", "expect": "reject", "why", "raw"}

Determinism: every seed is sha256 of a fixed domain string; envelopes
derive purely from those seeds. Re-running reproduces the corpora
byte-for-byte.

Regenerate:

    python3 scripts/keripy_ipex_gen.py \
      --out-dir crates/keri-codec/tests/corpus/ipex
"""

import argparse
import base64
import hashlib
import json
from pathlib import Path

import blake3
from nacl.signing import SigningKey

KERIPY_PIN = "de59bc7d834955c5b0273c62f6b8b6a0df150dc3"

SAID_LEN = 44  # `E` code byte + 32-byte digest = 33 qb2 bytes = 44 sextets
SAID_DUMMY = "#" * SAID_LEN

# Fixed deterministic timestamp in keripy `nowiso` shape.
DT_EXN = "2026-09-17T12:00:00.000000+00:00"

# CESR base64url alphabet.
B64URL = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"

HAPPY = "happy.jsonl"
SIGNED = "signed.jsonl"
HARDEN = "harden.jsonl"


def qb64(code: str, raw: bytes) -> str:
    """CESR qb64 for `raw` under selector `code`, per keripy `Matter`: the
    code's sextets are left-aligned in their qb2 bytes and the raw bytes
    follow BYTE-ALIGNED — for one-sextet codes the code byte is the sextet
    value shifted into the top 6 bits, then the raw stream. Not `code +
    b64(raw)`: that shifts the raw by 2 bits and produces a different
    (invalid) primitive."""
    acc, bits = 0, 0
    for ch in code:
        acc = (acc << 6) | B64URL.index(ch)
        bits += 6
    pad = (-bits) % 8
    code_bytes = (acc << pad).to_bytes((bits + pad) // 8, "big")
    return base64.urlsafe_b64encode(code_bytes + raw).decode().rstrip("=")


def domain_seed(name: str) -> bytes:
    return hashlib.sha256(b"keripy-ipex-parity:" + name.encode()).digest()


def sender_prefix() -> str:
    """The exchange sender's transferable Ed25519 verification key qb64
    (`D` + 43)."""
    raw = SigningKey(domain_seed("sender")).verify_key.encode()
    return qb64("D", raw)


def issuer_prefix() -> str:
    """The embedded credential's issuer prefix qb64 (`D` + 43)."""
    raw = SigningKey(domain_seed("issuer")).verify_key.encode()
    return qb64("D", raw)


def issuee_prefix() -> str:
    """The embedded credential's issuee prefix qb64 (`D` + 43)."""
    raw = SigningKey(domain_seed("issuee")).verify_key.encode()
    return qb64("D", raw)


def schema_said() -> str:
    """A Blake3-256 schema SAID qb64 (`E` + 43) over fixed domain bytes."""
    digest = blake3.blake3(domain_seed("schema")).digest()
    return qb64("E", digest)


def registry_said() -> str:
    """A Blake3-256 registry SAID qb64 (`E` + 43) — the embedded
    credential's TEL registry."""
    digest = blake3.blake3(domain_seed("registry")).digest()
    return qb64("E", digest)


def nonce_qb64() -> str:
    """A Salt_128 salty-uuid nonce qb64 (`0A` + 22 over 16 raw bytes)."""
    raw = domain_seed("nonce")[:16]
    return qb64("0A", raw)


def sender_signing_key() -> SigningKey:
    return SigningKey(domain_seed("sender"))


def saidify_bare_map(mkd: dict) -> bytes:
    """Saidify one bare canonical JSON object per keripy `Saider.saidify`:
    no version string, no size patch — digest the map with the `d` slot
    dummied and splice the resulting `E...` qb64 back in.

    Self-checking: after splicing, the slot is re-dummied and re-digested
    to confirm the recorded SAID reproduces (keripy's `Saider.verify`
    contract)."""
    raw = json.dumps(mkd, separators=(",", ":"), ensure_ascii=False).encode()
    digest = blake3.blake3(raw).digest()
    said = qb64("E", digest)
    assert len(said) == SAID_LEN, "said width must be 44"
    slot = f'"d":"{SAID_DUMMY}"'.encode()
    assert slot in raw, "bare map must carry a dummied d slot"
    spliced = raw.replace(slot, f'"d":"{said}"'.encode())
    # Self-check: re-dummy and confirm the digest reproduces.
    scratch = spliced.replace(f'"d":"{said}"'.encode(), slot)
    assert blake3.blake3(scratch).digest() == digest, "SAID self-check failed"
    return spliced


def saidify_versioned(ked: dict, head: bytes) -> bytes:
    """Saidify one canonical versioned event body per keripy `SerderKERI`
    `makify`: patch the version size, digest the body with the `d` slot
    dummied, and splice the resulting `E...` qb64 back in.

    Self-checking: after splicing, the slot is re-dummied and re-digested
    to confirm the recorded SAID reproduces, and the version string is
    confirmed to record the body's own byte size."""
    raw = json.dumps(ked, separators=(",", ":"), ensure_ascii=False).encode()
    assert raw.startswith(head), "version placeholder"
    size = len(raw)
    raw = head.replace(b"000000", f"{size:06x}".encode()) + raw[len(head):]
    digest = blake3.blake3(raw).digest()
    said = qb64("E", digest)
    assert len(said) == SAID_LEN, "said width must be 44"
    slot = f'"d":"{SAID_DUMMY}"'.encode()
    assert slot in raw, "event must carry a dummied d slot"
    spliced = raw.replace(slot, f'"d":"{said}"'.encode(), 1)
    # Self-check: re-dummy and confirm the digest reproduces.
    scratch = spliced.replace(f'"d":"{said}"'.encode(), slot, 1)
    assert blake3.blake3(scratch).digest() == digest, "SAID self-check failed"
    decoded = json.loads(spliced)
    protocol = "KERI" if head.startswith(b'{"v":"KERI') else "ACDC"
    assert decoded["v"] == f"{protocol}10JSON{len(spliced):06x}_", (
        "version size self-check failed"
    )
    return spliced


KERI_HEAD = b'{"v":"KERI10JSON000000_"'
ACDC_HEAD = b'{"v":"ACDC10JSON000000_"'
EXN_HEAD = KERI_HEAD


def said_of(raw: bytes) -> str:
    """The recorded `d` qb64 of a finished event body."""
    start = raw.index(b'"d":"') + 5
    return raw[start : start + SAID_LEN].decode()


def embed_credentials() -> dict:
    """The ACDC credential body embedded in the offer/grant envelopes —
    a compact issuance credential, saidified inner-out first."""
    ked = {
        "v": "ACDC10JSON000000_",
        "d": SAID_DUMMY,
        "u": nonce_qb64(),
        "i": issuer_prefix(),
        "ri": registry_said(),
        "s": schema_said(),
        "a": json.loads(
            saidify_bare_map(
                {
                    "d": SAID_DUMMY,
                    "i": issuee_prefix(),
                    "title": "Quarterly report",
                }
            )
        ),
    }
    return {"raw": saidify_versioned(ked, ACDC_HEAD)}


def embed_iss_event(credential_said: str) -> dict:
    """The TEL `iss` event body embedded in the grant envelope — a full
    saidified registry issuance (typed on the Rust side).

    The TEL `iss` law names the credential, not the actor: its `i` is the
    issued credential's SAID and its `s` is pinned at 0 (the registry's
    first issuance), matching the verified TEL corpus."""
    ked = {
        "v": "KERI10JSON000000_",
        "t": "iss",
        "d": SAID_DUMMY,
        "i": credential_said,
        "s": "0",
        "ri": registry_said(),
        "dt": DT_EXN,
    }
    return {"raw": saidify_versioned(ked, KERI_HEAD)}


def prior_said() -> str:
    """A fabricated deterministic E-prefix standing in for the issuer's
    prior KEL event digest — the corpus pins wire shapes, not a real
    issuer KEL chain."""
    digest = blake3.blake3(domain_seed("issuer-kel-prior")).digest()
    return qb64("E", digest)


def embed_anc_event(iss_said: str) -> dict:
    """The KEL `ixn` anchor body embedded in the grant envelope — a saidified
    interaction event (generic block on the Rust side).

    The ixn grammar is `v,t,d,i,s,p,a` (no `dt`): the anchor list carries
    an event seal naming the embedded TEL issuance, and the prior is a
    fabricated deterministic digest."""
    ked = {
        "v": "KERI10JSON000000_",
        "t": "ixn",
        "d": SAID_DUMMY,
        "i": issuer_prefix(),
        "s": "1",
        "p": prior_said(),
        "a": [{"i": issuer_prefix(), "s": "0", "d": iss_said}],
    }
    return {"raw": saidify_versioned(ked, KERI_HEAD)}


def saidify_embeds_map(embeds: dict) -> bytes:
    """Saidify the exn embeds map per keripy `Saider.saidify`: entries in
    route order, then the map's own dummied `d` LAST — no version string,
    no size patch."""
    mkd = dict(embeds)
    mkd["d"] = SAID_DUMMY
    return saidify_bare_map(mkd)


def exchange(sender: str, route: str, payload: dict, embeds: dict | None,
             prior: str | None) -> bytes:
    """One saidified `exn` envelope per keripy `Exchange`/`specialExchange`:
    `v,t,d,i,rp,p,dt,r,q,a[,e]` with the embeds map saidified per-label
    and always carrying its trailing `d`."""
    ked = {
        "v": "KERI10JSON000000_",
        "t": "exn",
        "d": SAID_DUMMY,
        "i": sender,
        "rp": "",
        "p": prior if prior is not None else "",
        "dt": DT_EXN,
        "r": route,
        "q": {},
        "a": payload,
    }
    if embeds is not None:
        ked["e"] = json.loads(saidify_embeds_map(embeds))
    return saidify_versioned(ked, EXN_HEAD)


def sign(raw: bytes) -> dict:
    """The sender's Ed25519 signature over the final envelope bytes, as
    keripy `messagize` attaches it: an indexed-sig qb64 (`A` + index sextet
    + 86, key index 0) plus the sender's raw verification key for
    independent replay."""
    signed = sender_signing_key().sign(raw)
    # Ed25519 indexed signature: selector `A` + one index sextet (`A` = key
    # index 0) + the 64-byte signature — 88 qb64 chars, byte-aligned.
    sig_qb64 = qb64("AA", signed.signature)
    assert len(sig_qb64) == 88, "indexed Ed25519 signature qb64 must be 88"
    return {
        "vk_b64": base64.b64encode(
            sender_signing_key().verify_key.encode()
        ).decode(),
        "sig_qb64": sig_qb64,
    }


def happy_vectors() -> list:
    """(case, route, raw) tuples — the six IPEX routes at their verified
    factory shapes, with the offer/grant embeds populated."""
    sender = sender_prefix()
    acdc = embed_credentials()
    iss = embed_iss_event(json.loads(acdc["raw"])["d"])
    anc = embed_anc_event(json.loads(iss["raw"])["d"])

    apply_raw = exchange(
        sender,
        "/ipex/apply",
        {"m": "apply for credential", "s": schema_said(),
         "a": {"role": "holder"}, "i": issuee_prefix()},
        None,
        None,
    )
    offer_raw = exchange(
        sender,
        "/ipex/offer",
        {"m": "here is your credential offer"},
        {"acdc": json.loads(acdc["raw"])},
        None,
    )
    agree_raw = exchange(
        sender,
        "/ipex/agree",
        {"m": "i agree to your offer"},
        None,
        said_of(offer_raw),
    )
    grant_raw = exchange(
        sender,
        "/ipex/grant",
        {"m": "here is your credential", "i": issuee_prefix()},
        {
            "acdc": json.loads(acdc["raw"]),
            "iss": json.loads(iss["raw"]),
            "anc": json.loads(anc["raw"]),
        },
        said_of(agree_raw),
    )
    grant_minimal_raw = exchange(
        sender,
        "/ipex/grant",
        {"m": "minimal grant", "i": issuee_prefix()},
        {"acdc": json.loads(acdc["raw"])},
        said_of(agree_raw),
    )
    admit_raw = exchange(
        sender,
        "/ipex/admit",
        {"m": "i admit your grant"},
        None,
        said_of(grant_raw),
    )
    spurn_raw = exchange(
        sender,
        "/ipex/spurn",
        {"m": "i do not want this credential"},
        None,
        said_of(offer_raw),
    )
    return [
        ("apply", "/ipex/apply", apply_raw),
        ("offer", "/ipex/offer", offer_raw),
        ("agree", "/ipex/agree", agree_raw),
        ("grant", "/ipex/grant", grant_raw),
        ("grant_minimal", "/ipex/grant", grant_minimal_raw),
        ("admit", "/ipex/admit", admit_raw),
        ("spurn", "/ipex/spurn", spurn_raw),
    ]


def harden_vectors() -> list:
    """(case, route, why, raw) tuples — parse-hardening rejects, each named
    by the law it violates. `level` distinguishes envelope-level (exn)
    from route-level (typed IPEX lift) rejections."""

    def unknown_route() -> bytes:
        return exchange(sender_prefix(), "/ipex/bogus", {"m": "?"}, None, None)

    def unknown_embed() -> bytes:
        # A grant carrying an embed label outside its verified shape.
        acdc = embed_credentials()
        return exchange(
            sender_prefix(),
            "/ipex/grant",
            {"m": "grant", "i": issuee_prefix()},
            {
                "acdc": json.loads(acdc["raw"]),
                "bogus": json.loads(saidify_bare_map({"d": SAID_DUMMY})),
            },
            None,
        )

    def offer_missing_acdc() -> bytes:
        # An offer must embed its credential — the empty embeds map breaks
        # the typed lift (e renders as {} without an acdc label).
        return exchange(
            sender_prefix(),
            "/ipex/offer",
            {"m": "offer without a credential"},
            {},
            None,
        )

    def apply_attributes_said() -> bytes:
        # The typed routes' payload is a map; the ESSR bare-SAID form has
        # no typed lift. An apply whose `a` is a bare SAID string.
        ked = {
            "v": "KERI10JSON000000_",
            "t": "exn",
            "d": SAID_DUMMY,
            "i": sender_prefix(),
            "rp": "",
            "p": "",
            "dt": DT_EXN,
            "r": "/ipex/apply",
            "q": {},
            "a": schema_said(),
        }
        return saidify_versioned(ked, EXN_HEAD)

    def tampered_embed_said() -> bytes:
        # The embeds map's own `d` names different bytes: the SAID of a
        # different map content is stored on an otherwise valid map, so the
        # structural scan succeeds and the map's SAID verification fails.
        acdc = embed_credentials()
        block = json.loads(acdc["raw"])
        embeds_raw = saidify_bare_map({"acdc": block, "d": SAID_DUMMY})
        other_raw = saidify_bare_map(
            {"acdc": block, "note": "tampered", "d": SAID_DUMMY}
        )
        ked = {
            "v": "KERI10JSON000000_",
            "t": "exn",
            "d": SAID_DUMMY,
            "i": sender_prefix(),
            "rp": "",
            "p": "",
            "dt": DT_EXN,
            "r": "/ipex/offer",
            "q": {},
            "a": {"m": "offer"},
            "e": {
                "acdc": json.loads(embeds_raw)["acdc"],
                "d": json.loads(other_raw)["d"],
            },
        }
        return saidify_versioned(ked, EXN_HEAD)

    def reordered_payload() -> bytes:
        # The apply payload map violates canonical key order (`s` before
        # `m`).
        return exchange(
            sender_prefix(),
            "/ipex/apply",
            {"s": schema_said(), "m": "apply", "a": {}, "i": issuee_prefix()},
            None,
            None,
        )

    def tampered_said() -> bytes:
        raw = exchange(
            sender_prefix(),
            "/ipex/agree",
            {"m": "agree"},
            None,
            schema_said(),
        )
        said = said_of(raw)
        other = qb64("E", blake3.blake3(domain_seed("tamper")).digest())
        assert other != said, "tamper digest must differ"
        return raw.replace(said.encode(), other.encode(), 1)

    def embeds_d_not_last() -> bytes:
        # The embeds map's own `d` must be its LAST entry.
        acdc = embed_credentials()
        ked = {
            "v": "KERI10JSON000000_",
            "t": "exn",
            "d": SAID_DUMMY,
            "i": sender_prefix(),
            "rp": "",
            "p": "",
            "dt": DT_EXN,
            "r": "/ipex/offer",
            "q": {},
            "a": {"m": "offer"},
            "e": {"d": SAID_DUMMY, "acdc": json.loads(acdc["raw"])},
        }
        return saidify_versioned(ked, EXN_HEAD)

    return [
        ("unknown_route", "/ipex/bogus", "route", "unknown_route", unknown_route()),
        ("unknown_embed", "/ipex/grant", "route", "unknown_embed", unknown_embed()),
        ("offer_missing_acdc", "/ipex/offer", "route", "missing_field", offer_missing_acdc()),
        ("apply_attributes_said", "/ipex/apply", "route", "attribute_said_form", apply_attributes_said()),
        ("tampered_embed_said", "/ipex/offer", "exn", "embeds_said_mismatch", tampered_embed_said()),
        ("reordered_payload", "/ipex/apply", "route", "non_canonical", reordered_payload()),
        ("tampered_said", "/ipex/agree", "exn", "said_mismatch", tampered_said()),
        ("embeds_d_not_last", "/ipex/offer", "exn", "non_canonical", embeds_d_not_last()),
    ]


def signed_records(happy: list) -> list:
    """The happy envelopes signed by the sender (keripy `messagize`
    content)."""
    records = []
    for case, route, raw in happy:
        record = {"case": case, "route": route, "kind": "message", "raw": raw.decode()}
        record.update(sign(raw))
        records.append(record)
    return records


def write_jsonl(path: Path, records: list) -> None:
    with open(path, "w", newline="\n") as handle:
        for record in records:
            handle.write(json.dumps(record, separators=(",", ":")) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="keripy IPEX parity generator (P4)")
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("crates/keri-codec/tests/corpus/ipex"),
        help="corpus output directory (default: the checked-in IPEX corpus)",
    )
    args = parser.parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)

    happy = happy_vectors()
    harden = harden_vectors()

    happy_records = [
        {
            "case": case,
            "route": route,
            "kind": "event",
            "raw": raw.decode(),
            "reserialize": "identical",
        }
        for case, route, raw in happy
    ]
    harden_records = [
        {
            "case": case,
            "route": route,
            "level": level,
            "expect": "reject",
            "why": why,
            "raw": raw.decode(),
        }
        for case, route, level, why, raw in harden
    ]

    write_jsonl(args.out_dir / HAPPY, happy_records)
    write_jsonl(args.out_dir / SIGNED, signed_records(happy))
    write_jsonl(args.out_dir / HARDEN, harden_records)

    total = len(happy_records) + len(harden_records)
    print(f"wrote {total} vectors to {args.out_dir}:")
    print(f"  {HAPPY}: {len(happy_records)} happy-path envelopes")
    print(f"  {SIGNED}: {len(happy_records)} sender-signed messages")
    print(f"  {HARDEN}: {len(harden_records)} parse-hardening rejects")
    print(f"keripy pin (shapes reproduced from, not imported): {KERIPY_PIN}")


if __name__ == "__main__":
    main()
