#!/usr/bin/env python3
"""keripy TEL parity generator (P3): deterministic happy + parse-hardening
vectors for the six registry-event ilks (vcp, vrt, iss, rev, bis, brv).

Mode: SHAPE REPRODUCTION at the keripy pin. The pinned keripy checkout
(`scripts/KERIPY_PIN`, de59bc7d) requires Python >= 3.14 while this
environment has 3.13, so this generator does NOT import keripy. Instead it
reproduces the pinned factories' wire shapes byte-for-byte from
`src/keri/vdr/eventing.py` at the pin:

- field order: vcp (v,t,d,i,ii,s,c,bt,b,n), vrt (v,t,d,i,p,s,bt,br,ba),
  iss (v,t,d,i,s,ri,dt), rev (v,t,d,i,s,ri,p,dt),
  bis (v,t,d,i,ii,s,ra,dt), brv (v,t,d,i,s,p,ra,dt);
- hexadecimal `s`/`bt` rendering (lowercase, no leading zeros);
- SAID derivation per keripy `Saider.saidify` / `SerderKERI(makify=True)`:
  each digestive slot (the `d`, plus the `i` for vcp) is replaced with a
  same-width dummy, the version size is patched, and blake3-256 over the
  whole body yields the `E...` qb64 spliced back into every slot;
- backed anchors: `ra = SealEvent(regk, regsn, regd)._asdict()` — ordered
  `i` (registry prefix), `s` (anchoring registry TEL sequence), `d` (the
  anchoring registry TEL event's digest);
- explicit `dt` ISO-8601 strings (deterministic — never wall-clock).

The SAIDs and signatures are REAL digests and real Ed25519 signatures —
independent `blake3` + `PyNaCl` reproduce exactly what keripy's `Saider`
and `ControllerIdxSigs` would emit — so the vectors are a genuine
wire-format differential, not placeholders. The corpus is marked PARTIAL
in `docs/keripy-parity/LEDGER.md` because it was not generated by
importing keripy itself (spec risk 3).

Output (JSONL, one record per line):
- `happy.jsonl`:  shape vectors —
  {"case", "ilk", "kind": "event", "raw", "reserialize": "identical"}
- `signed.jsonl`: the same events signed by the issuer —
  {"case", "ilk", "kind": "message", "raw", "vk_b64", "sig_qb64"}
- `harden.jsonl`: parse-hardening vectors —
  {"case", "ilk", "expect": "reject", "why", "raw"}

Determinism: every seed is sha256 of a fixed domain string; events derive
purely from those seeds and fixed timestamps. Re-running reproduces the
corpora byte-for-byte.

Regenerate:

    python3 scripts/keripy_tel_gen.py \
      --out-dir crates/keri-codec/tests/corpus/tel
"""

import argparse
import base64
import hashlib
import json
from pathlib import Path

import blake3
from nacl.signing import SigningKey

KERIPY_PIN = "de59bc7d834955c5b0273c62f6b8b6a0df150dc3"

# Fixed timestamp domain (deterministic; the factory contracts take `dt`).
DT_ISSUE = "2020-08-22T17:50:08.325000+00:00"
DT_REVOKE = "2020-08-22T17:50:09.325000+00:00"
DT_BIS = "2020-08-22T17:50:10.325000+00:00"
DT_BRV = "2020-08-22T17:50:10.825000+00:00"

SAID_LEN = 44  # `E` code byte + 32-byte digest = 33 qb2 bytes = 44 sextets
SAID_DUMMY = "#" * SAID_LEN

# CESR base64url alphabet.
B64URL = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"

HAPPY = "happy.jsonl"
SIGNED = "signed.jsonl"
HARDEN = "harden.jsonl"


def qb64(code: str, raw: bytes) -> str:
    """CESR qb64 for `raw` under selector `code`, per keripy `Matter`: the
    code's sextets are left-aligned in their qb2 bytes and the raw bytes
    follow BYTE-ALIGNED — for one-sextet codes the code byte is the sextet
    value shifted into the top 6 bits, then the raw stream. Not `code +
    b64(raw)`: that shifts the raw by 2 bits and produces a different
    (invalid) primitive."""
    acc, bits = 0, 0
    for ch in code:
        acc = (acc << 6) | B64URL.index(ch)
        bits += 6
    pad = (-bits) % 8
    code_bytes = (acc << pad).to_bytes((bits + pad) // 8, "big")
    return base64.urlsafe_b64encode(code_bytes + raw).decode().rstrip("=")


def domain_seed(name: str) -> bytes:
    return hashlib.sha256(b"keripy-tel-parity:" + name.encode()).digest()


def issuer_qb64() -> str:
    """The issuer's transferable Ed25519 verification key qb64 (`D` + 43)."""
    raw = SigningKey(domain_seed("issuer")).verify_key.encode()
    return qb64("D", raw)


def backer_qb64(index: int) -> str:
    """A non-transferable Ed25519 backer prefix qb64 (`B` + 43)."""
    raw = SigningKey(domain_seed(f"backer-{index}")).verify_key.encode()
    return qb64("B", raw)


def credential_said(index: int) -> str:
    """A Blake3-256 credential SAID qb64 (`E` + 43) over fixed domain bytes."""
    digest = blake3.blake3(domain_seed(f"credential-{index}")).digest()
    return qb64("E", digest)


def registry_nonce_qb64() -> str:
    """A Salt_128 registry nonce qb64 (`0A` + 22 over 16 raw bytes)."""
    raw = domain_seed("nonce")[:16]
    return qb64("0A", raw)


def issuer_signing_key() -> SigningKey:
    return SigningKey(domain_seed("issuer"))


def saidify(ked: dict) -> bytes:
    """Saidify one canonical event body per keripy `makify`: patch the
    version size, digest the body with every digestive slot dummied, and
    splice the resulting `E...` qb64 back into each slot.

    Self-checking: after splicing, the slots are re-dummied and re-digested
    to confirm the recorded SAID reproduces (keripy's `Saider.verify`
    contract)."""
    labels = ("d", "i") if ked.get("t") == "vcp" else ("d",)
    raw = json.dumps(ked, separators=(",", ":"), ensure_ascii=False).encode()
    head = b'{"v":"KERI10JSON000000_"'
    assert raw.startswith(head), "version placeholder"
    size = len(raw)
    raw = f'{{"v":"KERI10JSON{size:06x}_"'.encode() + raw[len(head):]
    digest = blake3.blake3(raw).digest()
    said = qb64("E", digest)
    assert len(said) == SAID_LEN, "said width must be 44"
    existing = {}
    for label in labels:
        head = f'"{label}":"'.encode()
        start = raw.index(head) + len(head)
        existing[label] = raw[start : start + SAID_LEN]
    # Splice the said into every slot that was a dummy. A hardening vector
    # may pre-set a slot (e.g. vcp i != d, a body keripy's saidify cannot
    # emit — which is exactly why the parser must reject it); pre-set slots
    # stay intact, and the digest covers them as-is.
    spliced = [label for label in labels if existing[label] == SAID_DUMMY.encode()]
    for label in spliced:
        raw = raw.replace(
            f'"{label}":"{SAID_DUMMY}"'.encode(),
            f'"{label}":"{said}"'.encode(),
        )
    # Self-check: re-dummy exactly the spliced slots (pre-set slots keep
    # their value) and confirm the digest reproduces.
    scratch = raw
    for label in spliced:
        scratch = scratch.replace(
            f'"{label}":"{said}"'.encode(),
            f'"{label}":"{SAID_DUMMY}"'.encode(),
        )
    assert blake3.blake3(scratch).digest() == digest, "SAID self-check failed"
    # Self-check: the final body is valid canonical JSON whose version
    # string records the body's own byte size.
    decoded = json.loads(raw)
    assert decoded["v"] == f"KERI10JSON{len(raw):06x}_", "version size self-check failed"
    return raw


def said_of(raw: bytes) -> str:
    """The recorded `d` qb64 of a finished event body."""
    start = raw.index(b'"d":"') + 5
    return raw[start : start + SAID_LEN].decode()


def sign(raw: bytes) -> dict:
    """The issuer's Ed25519 signature over the final event bytes, as keripy
    `messagize` attaches it: an indexed-sig qb64 (`A` + index sextet + 86,
    key index 0) plus the issuer's raw verification key for independent
    replay."""
    signed = issuer_signing_key().sign(raw)
    # Ed25519 indexed signature: selector `A` + one index sextet (`A` = key
    # index 0) + the 64-byte signature — 88 qb64 chars, byte-aligned.
    sig_qb64 = qb64("AA", signed.signature)
    assert len(sig_qb64) == 88, "indexed Ed25519 signature qb64 must be 88"
    return {
        "vk_b64": base64.b64encode(issuer_signing_key().verify_key.encode()).decode(),
        "sig_qb64": sig_qb64,
    }


def vcp_two_backers() -> dict:
    return {
        "v": "KERI10JSON000000_",
        "t": "vcp",
        "d": SAID_DUMMY,
        "i": SAID_DUMMY,
        "ii": issuer_qb64(),
        "s": "0",
        "c": [],
        "bt": "1",
        "b": [backer_qb64(1), backer_qb64(2)],
        "n": registry_nonce_qb64(),
    }


def vcp_no_backers() -> dict:
    return {
        "v": "KERI10JSON000000_",
        "t": "vcp",
        "d": SAID_DUMMY,
        "i": SAID_DUMMY,
        "ii": issuer_qb64(),
        "s": "0",
        "c": ["NB"],
        "bt": "0",
        "b": [],
        "n": registry_nonce_qb64(),
    }


def happy_vectors() -> list:
    """The checked-in happy-path story: two registries, a backer rotation,
    an issue/revoke chain, and the backed pair anchored in the registry."""
    backer3 = backer_qb64(3)
    cred1 = credential_said(1)
    cred2 = credential_said(2)

    vcp_a = saidify(vcp_two_backers())
    regk = said_of(vcp_a)  # the registry identity IS the vcp SAID
    vcp_b = saidify(vcp_no_backers())
    vrt_a = saidify(
        {
            "v": "KERI10JSON000000_",
            "t": "vrt",
            "d": SAID_DUMMY,
            "i": regk,
            "p": regk,
            "s": "1",
            "bt": "1",
            "br": [backer_qb64(1)],
            "ba": [backer3],
        }
    )
    iss_a = saidify(
        {
            "v": "KERI10JSON000000_",
            "t": "iss",
            "d": SAID_DUMMY,
            "i": cred1,
            "s": "0",
            "ri": regk,
            "dt": DT_ISSUE,
        }
    )
    rev_a = saidify(
        {
            "v": "KERI10JSON000000_",
            "t": "rev",
            "d": SAID_DUMMY,
            "i": cred1,
            "s": "1",
            "ri": regk,
            "p": said_of(iss_a),
            "dt": DT_REVOKE,
        }
    )
    bis_a = saidify(
        {
            "v": "KERI10JSON000000_",
            "t": "bis",
            "d": SAID_DUMMY,
            "i": cred2,
            "ii": regk,
            "s": "0",
            "ra": {"i": regk, "s": "0", "d": regk},
            "dt": DT_BIS,
        }
    )
    brv_a = saidify(
        {
            "v": "KERI10JSON000000_",
            "t": "brv",
            "d": SAID_DUMMY,
            "i": cred2,
            "s": "1",
            "p": said_of(bis_a),
            "ra": {"i": regk, "s": "0", "d": said_of(bis_a)},
            "dt": DT_BRV,
        }
    )
    return [
        ("vcp_two_backers", "vcp", vcp_a),
        ("vcp_no_backers", "vcp", vcp_b),
        ("vrt_cuts_adds", "vrt", vrt_a),
        ("iss_basic", "iss", iss_a),
        ("rev_basic", "rev", rev_a),
        ("bis_backed", "bis", bis_a),
        ("brv_backed", "brv", brv_a),
    ]


def harden_vectors() -> list:
    """Parse-hardening vectors: each mutation is SAID-consistent (saidified
    over the mutated body) unless the case itself IS the SAID or
    canonicality failure, so the recorded `why` names the single law that
    must reject."""
    backer1 = backer_qb64(1)
    backer2 = backer_qb64(2)
    cred1 = credential_said(1)
    cred2 = credential_said(2)

    vcp_a = saidify(vcp_two_backers())
    regk = said_of(vcp_a)

    # vcp with i != d: the registry identity is not self-addressing.
    ked = vcp_two_backers()
    ked["i"] = cred1
    mismatch = saidify(ked)

    # iss at s=1 (pinned 0) and rev at s=0 (pinned 1).
    ked = {
        "v": "KERI10JSON000000_",
        "t": "iss",
        "d": SAID_DUMMY,
        "i": cred1,
        "s": "1",
        "ri": regk,
        "dt": DT_ISSUE,
    }
    iss_pinned = saidify(ked)
    ked = {
        "v": "KERI10JSON000000_",
        "t": "rev",
        "d": SAID_DUMMY,
        "i": cred1,
        "s": "0",
        "ri": regk,
        "p": said_of(iss_pinned),
        "dt": DT_REVOKE,
    }
    ked["s"] = "0"
    rev_pinned = saidify(ked)

    # bt=2 over a one-backer set: out of bounds.
    ked = {
        "v": "KERI10JSON000000_",
        "t": "vcp",
        "d": SAID_DUMMY,
        "i": SAID_DUMMY,
        "ii": issuer_qb64(),
        "s": "0",
        "c": [],
        "bt": "2",
        "b": [backer1],
        "n": registry_nonce_qb64(),
    }
    toad_over = saidify(ked)

    # Non-canonical JSON: a space after the first comma. The version header
    # is re-spliced to the tampered size first so the scanner must reject the
    # JSON itself (non-canonical), not a stale size (SAID untouched — the
    # scanner rejects before any digest work).
    non_canonical = vcp_a.replace(b'",', b'", ', 1)
    size_marker = b'"v":"KERI10JSON'
    vm = non_canonical.index(size_marker) + len(size_marker)
    size_field = f"{len(non_canonical):06X}".encode()
    non_canonical = non_canonical[:vm] + size_field + non_canonical[vm + 6:]

    # Tampered SAID: flip the d code (E -> F) on a well-formed iss.
    ked = {
        "v": "KERI10JSON000000_",
        "t": "iss",
        "d": SAID_DUMMY,
        "i": cred1,
        "s": "0",
        "ri": regk,
        "dt": DT_ISSUE,
    }
    tampered = bytearray(saidify(ked))
    d_code_at = tampered.index(b'"d":"E') + 5
    tampered[d_code_at] = ord("F")
    tampered = bytes(tampered)

    # Reordered iss: dt before ri (every value canonical; only order fails).
    reordered = saidify(
        {
            "v": "KERI10JSON000000_",
            "t": "iss",
            "d": SAID_DUMMY,
            "i": cred1,
            "s": "0",
            "dt": DT_ISSUE,
            "ri": regk,
        }
    )

    # Digest-shaped and source-shaped ra anchors on backed events (both are
    # lawful seals elsewhere in KERI; the TEL backer anchor must be Event).
    bis_digest_anchor = saidify(
        {
            "v": "KERI10JSON000000_",
            "t": "bis",
            "d": SAID_DUMMY,
            "i": cred2,
            "ii": regk,
            "s": "0",
            "ra": {"d": regk},
            "dt": DT_BIS,
        }
    )
    brv_source_anchor = saidify(
        {
            "v": "KERI10JSON000000_",
            "t": "brv",
            "d": SAID_DUMMY,
            "i": cred2,
            "s": "1",
            "p": said_of(iss_pinned),
            "ra": {"s": "0", "d": regk},
            "dt": DT_BRV,
        }
    )

    # Unknown TEL ilk.
    unknown = saidify(
        {
            "v": "KERI10JSON000000_",
            "t": "vxp",
            "d": SAID_DUMMY,
            "i": cred1,
            "s": "0",
            "ri": regk,
            "dt": DT_ISSUE,
        }
    )

    return [
        ("vcp_registry_identity_mismatch", "vcp", "registry_identity", mismatch),
        ("iss_sequence_one", "iss", "pinned_sequence", iss_pinned),
        ("rev_sequence_zero", "rev", "pinned_sequence", rev_pinned),
        ("vcp_toad_over_backers", "vcp", "toad_bounds", toad_over),
        ("vcp_non_canonical_json", "vcp", "non_canonical", non_canonical),
        ("iss_tampered_said", "iss", "said_mismatch", tampered),
        ("iss_reordered_fields", "iss", "field_order", reordered),
        ("bis_digest_anchor", "bis", "anchor_shape", bis_digest_anchor),
        ("brv_source_anchor", "brv", "anchor_shape", brv_source_anchor),
        ("unknown_tel_ilk", "vxp", "unknown_ilk", unknown),
    ]


def signed_records(happy: list) -> list:
    """The happy events signed by the issuer (keripy `messagize` content)."""
    records = []
    for case, ilk, raw in happy:
        record = {"case": case, "ilk": ilk, "kind": "message", "raw": raw.decode()}
        record.update(sign(raw))
        records.append(record)
    return records


def write_jsonl(path: Path, records: list) -> None:
    with open(path, "w", newline="\n") as handle:
        for record in records:
            handle.write(json.dumps(record, separators=(",", ":")) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="keripy TEL parity generator (P3)")
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("crates/keri-codec/tests/corpus/tel"),
        help="corpus output directory (default: the checked-in TEL corpus)",
    )
    args = parser.parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)

    happy = happy_vectors()
    harden = harden_vectors()

    happy_records = [
        {
            "case": case,
            "ilk": ilk,
            "kind": "event",
            "raw": raw.decode(),
            "reserialize": "identical",
        }
        for case, ilk, raw in happy
    ]
    harden_records = [
        {
            "case": case,
            "ilk": ilk,
            "expect": "reject",
            "why": why,
            "raw": raw.decode(),
        }
        for case, ilk, why, raw in harden
    ]

    write_jsonl(args.out_dir / HAPPY, happy_records)
    write_jsonl(args.out_dir / SIGNED, signed_records(happy))
    write_jsonl(args.out_dir / HARDEN, harden_records)

    total = len(happy_records) + len(harden_records)
    print(f"wrote {total} vectors to {args.out_dir}:")
    print(f"  {HAPPY}: {len(happy_records)} happy-path events")
    print(f"  {SIGNED}: {len(happy_records)} issuer-signed messages")
    print(f"  {HARDEN}: {len(harden_records)} parse-hardening rejects")
    print(f"keripy pin (shapes reproduced from, not imported): {KERIPY_PIN}")


if __name__ == "__main__":
    main()
